"""Generate the SYNTHETIC DEX fill recordings (decision on DEX fills).

Nothing here exists on any network. Accounts, transaction hashes and the SYNUSD asset are
derived from ``invaria:synthetic:stellar:*`` labels (shared with build_path_payments.py).
The responses imitate the shapes of Horizon ``/accounts/{id}/payments``,
``/transactions/{hash}/operations`` and ``/operations/{id}/effects`` and of RPC
``getEvents`` seen in the real recordings (``usdc-gbain6``, ``usdc-issuer-fill``); every
response body carries ``"_synthetic"``.

What the real samples cannot show is covered here: the watched account's own offer
operation crossing others, two of its offers crossed by one operation, a trade that does
not add up to the SAC event, a fill without its Classic trade, an origin that is not a DEX
operation, an operation Horizon does not find, an effects page too long to be complete, a
contract call missing from the payments listing, and a listed payment (no lookup at all).
A second target (``target-offer-owner.json``, O1) shares the store-relevant asset: the
event of case 2 is A's fill as taker and O1's fill as maker, seen from each side.
The unsupported-type case uses ``claim_claimable_balance`` with account parties only to
exercise that branch: a real claim emits its claimable balance as a party.

Regenerate (an explicit decision; the tests pin the resulting effects):
    uv run --locked python tests/fixtures/stellar/synthetic/build_dex_fills.py
"""

from __future__ import annotations

import json
import shutil
import sys
import tempfile
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, urlsplit

sys.path.insert(0, str(Path(__file__).resolve().parent))

from build_path_payments import (  # noqa: E402
    CONTRACT,
    EURX,
    PASSPHRASE,
    SYNUSD,
    DeterministicRecorder,
    _asset_fields,
    account,
    sc_account,
    sc_i128,
    sc_string,
    sc_symbol,
    tx_hash,
)

from invaria.contracts.base import parse_contract  # noqa: E402
from invaria.contracts.chain import ChainTarget  # noqa: E402
from invaria.stellar.adapter import ingest_horizon_payments, ingest_sac_events  # noqa: E402
from invaria.stellar.http import Response  # noqa: E402
from invaria.stellar.sources import Horizon, Rpc, verify_network  # noqa: E402
from invaria.stellar.store import IngestStore  # noqa: E402

HERE = Path(__file__).resolve().parent
OUT = HERE / "dex-fills"
MARK = "SYNTHETIC: generated by build_dex_fills.py; does not exist on any network"
NETWORK = "stellar:testnet"
START, END = 90000200, 90000215
ELDER, LATEST = 90000000, 90000300
BASE_TIME = datetime(2026, 10, 7, 9, 0, tzinfo=UTC)
HORIZON_URL = "https://horizon.synthetic.invalid"
RPC_URL = "https://rpc.synthetic.invalid"
EFFECTS_LIMIT = 200

A = account("dex-watched")  # the target account (offer owner or taker)
E = account("dex-payer")
P1, P2, P3, P4, P5 = (account(f"dex-taker-{i}") for i in range(1, 6))
O1 = account("dex-offer-owner-1")
B = account("dex-destination")


def close_time(ledger: int) -> str:
    return (BASE_TIME + timedelta(seconds=5 * (ledger - START))).strftime("%Y-%m-%dT%H:%M:%SZ")


def toid(ledger: int, op_index: int) -> int:
    return (ledger << 32) | (1 << 12) | (op_index + 1)


class Case:
    """One transaction with a single operation, its SAC events and its Horizon views."""

    def __init__(self, label: str, ledger: int, kind: str, source: str, fields: dict[str, Any]):
        self.label, self.ledger, self.kind, self.source = label, ledger, kind, source
        self.fields = fields
        self.events: list[dict[str, Any]] = []
        self.effects: list[dict[str, Any]] = []
        self.listed = False  # in A's payments
        self.found = True  # Horizon knows the transaction

    @property
    def hash(self) -> str:
        return tx_hash(f"dex:{self.label}")

    @property
    def op_id(self) -> str:
        return str(toid(self.ledger, 0))

    def operation(self) -> dict[str, Any]:
        return {
            "id": self.op_id,
            "paging_token": self.op_id,
            "transaction_successful": True,
            "source_account": self.source,
            "type": self.kind,
            "created_at": close_time(self.ledger),
            "transaction_hash": self.hash,
            **self.fields,
        }

    def transfer(self, src: str, dst: str, atoms: int) -> Case:
        asset = sc_string(f"{SYNUSD[0]}:{SYNUSD[1]}")
        index = len(self.events) + 1
        self.events.append(
            {
                "type": "contract",
                "ledger": self.ledger,
                "ledgerClosedAt": close_time(self.ledger),
                "contractId": CONTRACT,
                "id": f"{toid(self.ledger, 0):019d}-{index:010d}",
                "operationIndex": 0,
                "transactionIndex": 1,
                "txHash": self.hash,
                "inSuccessfulContractCall": True,
                "topic": [sc_symbol("transfer"), sc_account(src), sc_account(dst), asset],
                "value": sc_i128(atoms),
            }
        )
        return self

    def trade(
        self,
        who: str,
        seller: str,
        offer: int,
        sold: tuple[str, str] | None,
        sold_amount: str,
        bought: tuple[str, str] | None,
        bought_amount: str,
    ) -> Case:
        index = len(self.effects) + 1
        self.effects.append(
            {
                "id": f"{toid(self.ledger, 0):019d}-{index:010d}",
                "paging_token": f"{toid(self.ledger, 0)}-{index}",
                "type": "trade",
                "type_i": 33,
                "account": who,
                "seller": seller,
                "offer_id": str(offer),
                "created_at": close_time(self.ledger),
                "sold_amount": sold_amount,
                **_asset_fields(sold, "sold_"),
                "bought_amount": bought_amount,
                **_asset_fields(bought, "bought_"),
            }
        )
        return self


def _offer(selling: tuple[str, str], buying: tuple[str, str], amount: str) -> dict[str, Any]:
    return {
        "amount": amount,
        "price": "1.1000000",
        "offer_id": "0",
        **_asset_fields(selling, "selling_"),
        **_asset_fields(buying, "buying_"),
    }


def _path(sender: str, receiver: str) -> dict[str, Any]:
    return {
        "from": sender,
        "to": receiver,
        **_asset_fields(EURX),
        "amount": "3.0000000",
        **_asset_fields(EURX, "source_"),
        "source_amount": "3.3000000",
        "destination_min": "2.9000000",
        "path": [_asset_fields(SYNUSD)],
    }


def world() -> list[Case]:
    cases: list[Case] = []
    # 1. P1's path payment EURX -> SYNUSD -> EURX crosses A's offer selling SYNUSD.
    cases.append(
        Case("fill-maker-path", 90000201, "path_payment_strict_send", P1, _path(P1, B))
        .transfer(A, P1, 30000000)
        .transfer(P1, B, 33000000)  # does not involve A: ignored
        .trade(A, P1, 7001, SYNUSD, "3.0000000", EURX, "3.3000000")
        .trade(P1, A, 7001, EURX, "3.3000000", SYNUSD, "3.0000000")
    )
    # 2. A's own manage_sell_offer (selling EURX for SYNUSD) crosses O1's offer.
    cases.append(
        Case("fill-taker-manage", 90000202, "manage_sell_offer", A, _offer(EURX, SYNUSD, "2.2"))
        .transfer(O1, A, 20000000)
        .trade(A, O1, 7002, EURX, "2.2000000", SYNUSD, "2.0000000")
        .trade(O1, A, 7002, SYNUSD, "2.0000000", EURX, "2.2000000")
    )
    # 3. P2's manage_buy_offer crosses two offers of A: two fills, net and gross compared.
    cases.append(
        Case("fill-two-offers", 90000203, "manage_buy_offer", P2, _offer(EURX, SYNUSD, "2.5"))
        .transfer(A, P2, 10000000)
        .transfer(A, P2, 15000000)
        .trade(A, P2, 7003, SYNUSD, "1.0000000", EURX, "1.1000000")
        .trade(A, P2, 7004, SYNUSD, "1.5000000", EURX, "1.6500000")
    )
    # 4. The SAC event says 4 SYNUSD; the trade effect says 3: a conflict, both kept.
    cases.append(
        Case("fill-conflict", 90000204, "manage_sell_offer", P3, _offer(EURX, SYNUSD, "4.4"))
        .transfer(A, P3, 40000000)
        .trade(A, P3, 7005, SYNUSD, "3.0000000", EURX, "3.3000000")
    )
    # 5. A DEX operation without a Classic trade of A: its type alone proves no fill.
    cases.append(
        Case("fill-sac-only", 90000205, "create_passive_sell_offer", P4, _offer(EURX, SYNUSD, "1.1"))
        .transfer(A, P4, 10000000)
        .trade(P4, A, 7006, EURX, "1.1000000", SYNUSD, "1.0000000")
    )
    # 6. An origin that is not a DEX operation nor a movement (unrealistic parties, see doc).
    cases.append(
        Case("unresolved-type", 90000206, "claim_claimable_balance", E, {"balance_id": "00" * 36})
        .transfer(E, A, 5000000)
    )
    # 7. Horizon does not know the transaction.
    unknown = Case("unresolved-not-found", 90000207, "manage_sell_offer", P5, {}).transfer(
        A, P5, 6000000
    )
    unknown.found = False
    cases.append(unknown)
    # 8. Too many effects to be sure the page holds every trade of A.
    noisy = Case("fill-incomplete", 90000208, "manage_sell_offer", P5, _offer(EURX, SYNUSD, "9"))
    noisy.transfer(A, P5, 7000000)
    noisy.trade(A, P5, 7008, SYNUSD, "0.7000000", EURX, "0.7700000")  # A's trade is there...
    for _ in range(EFFECTS_LIMIT - 1):  # ...but the page is full: more may exist
        noisy.trade(P5, O1, 7007, EURX, "0.0000001", SYNUSD, "0.0000001")
    cases.append(noisy)
    # 9. A contract call that Horizon did not list for A: still a token movement.
    cases.append(
        Case("unlisted-invoke", 90000209, "invoke_host_function", E, {"function": "HostFunctionTypeHostFunctionTypeInvokeContract"})
        .transfer(E, A, 8000000)
    )
    # 10. A payment E -> A that Horizon lists: a token movement, and no lookup at all.
    listed = Case(
        "listed-payment",
        90000210,
        "payment",
        E,
        {"from": E, "to": A, **_asset_fields(SYNUSD), "amount": "0.9000000"},
    ).transfer(E, A, 9000000)
    listed.listed = True
    cases.append(listed)
    return cases


class SyntheticNetwork:
    def __init__(self) -> None:
        self.cases = world()

    def request(self, method: str, url: str, body: bytes | None) -> Response:
        parts = urlsplit(url)
        if method == "POST":
            return self._rpc(json.loads(body or b"{}"))
        query = {k: v[0] for k, v in parse_qs(parts.query).items()}
        path = parts.path
        by_hash = {c.hash: c for c in self.cases}
        by_op = {c.op_id: c for c in self.cases}
        if path == "/":
            doc: dict[str, Any] = {
                "network_passphrase": PASSPHRASE,
                "history_elder_ledger": ELDER,
                "history_latest_ledger": LATEST,
                "current_protocol_version": 23,
            }
        elif path.startswith("/ledgers/"):
            sequence = int(path.rsplit("/", 1)[1])
            doc = {"sequence": sequence, "closed_at": close_time(sequence)}
        elif path == "/assets":
            doc = {"_embedded": {"records": []}}
        elif path.startswith("/accounts/") and path.endswith("/payments"):
            owner = path.split("/")[2]
            cursor, limit = int(query["cursor"]), int(query["limit"])
            records = []
            for case in self.cases:
                involved = owner in (case.fields.get("from"), case.fields.get("to"))
                if case.listed and involved and int(case.op_id) > cursor:
                    records.append(
                        {
                            **case.operation(),
                            "transaction": {
                                "hash": case.hash,
                                "ledger": case.ledger,
                                "successful": True,
                                "source_account": case.source,
                                "fee_account": case.source,
                                "fee_charged": "100",
                            },
                        }
                    )
            doc = {"_embedded": {"records": records[:limit]}}
        elif path.startswith("/transactions/") and path.endswith("/operations"):
            case = by_hash.get(path.split("/")[2])
            if case is None or not case.found:
                return Response(404, _body({"status": 404, "title": "Resource Missing"}))
            doc = {"_embedded": {"records": [case.operation()]}}
        elif path.startswith("/operations/") and path.endswith("/effects"):
            case = by_op.get(path.split("/")[2])
            if case is None:
                return Response(404, _body({"status": 404, "title": "Resource Missing"}))
            doc = {"_embedded": {"records": case.effects[: int(query["limit"])]}}
        else:
            return Response(404, _body({"status": 404}))
        return Response(200, _body(doc))

    def _rpc(self, request: dict[str, Any]) -> Response:
        if request["method"] == "getNetwork":
            return Response(
                200, _body({"jsonrpc": "2.0", "id": 1, "result": {"passphrase": PASSPHRASE}})
            )
        params = request["params"]
        pagination = params["pagination"]
        events = [e for c in self.cases for e in c.events]
        if "cursor" in pagination:
            pool = [e for e in events if e["id"] > pagination["cursor"]]
        else:
            pool = [
                e for e in events if params["startLedger"] <= e["ledger"] < params["endLedger"]
            ]
        chunk = pool[: pagination["limit"]]
        scanned = params.get("endLedger", LATEST + 1)
        cursor = (
            chunk[-1]["id"]
            if len(chunk) == pagination["limit"]
            else f"{(scanned << 32) - 1:019d}-4294967295"
        )
        result = {"events": chunk, "latestLedger": LATEST, "oldestLedger": ELDER, "cursor": cursor}
        return Response(200, _body({"jsonrpc": "2.0", "id": 1, "result": result}))


def _body(document: dict[str, Any]) -> bytes:
    return json.dumps({"_synthetic": MARK, **document}, indent=1, sort_keys=True).encode() + b"\n"


class Recorder(DeterministicRecorder):
    def request(self, method: str, url: str, body: bytes | None) -> Response:
        response = super().request(method, url, body)
        from invaria.stellar.http import request_key

        meta_path = self.directory / f"{request_key(method, url, body)}.json"
        meta = json.loads(meta_path.read_text("utf-8"))
        meta["synthetic"] = MARK
        meta["captured_at"] = "2026-10-07T00:00:00+00:00"
        meta_path.write_text(json.dumps(meta, indent=2, sort_keys=True) + "\n", "utf-8")
        return response


def target_document(account_id: str = A, target_id: str = "synthetic-synusd-dex-fills") -> dict[str, Any]:
    return {
        "schema_version": "1.0",
        "target_id": target_id,
        "tenant_id": "tenant-synthetic-stellar",
        "network": NETWORK,
        "asset_code": SYNUSD[0],
        "asset_issuer": SYNUSD[1],
        "account": account_id,
        "unit": "SYNUSD",
        "instrument_id": f"synthetic:asset:{SYNUSD[0]}:{SYNUSD[1]}",
        "representation_id": f"rep-synthetic-classic-{SYNUSD[0]}-{SYNUSD[1]}",
        "source_id": "stellar-synthetic",
        "expected_sac_contract_id": CONTRACT,
        "synthetic": True,
        "description": "SYNTHETIC DEX fill cases (build_dex_fills.py). The "
        "accounts, transactions and the SYNUSD asset do not exist on any network.",
    }


def main() -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    recordings = OUT / "recordings"
    target_path = OUT / "target.json"
    OUT.mkdir(parents=True)
    target_path.write_text(json.dumps(target_document(), indent=2) + "\n", "utf-8")
    owner_path = OUT / "target-offer-owner.json"
    owner_doc = target_document(O1, "synthetic-synusd-dex-fills-offer-owner")
    owner_path.write_text(json.dumps(owner_doc, indent=2) + "\n", "utf-8")
    target = parse_contract(ChainTarget, target_path.read_text("utf-8"))
    owner = parse_contract(ChainTarget, owner_path.read_text("utf-8"))
    client = Recorder(SyntheticNetwork(), recordings)  # type: ignore[arg-type]
    horizon, rpc = Horizon(HORIZON_URL, client), Rpc(RPC_URL, client)
    check = verify_network(horizon, rpc, NETWORK)
    recorded_at = datetime(2026, 10, 7, 10, 0, tzinfo=UTC)
    with tempfile.TemporaryDirectory() as tmp:
        store = IngestStore(Path(tmp))
        for chosen in (target, owner):
            ingest_horizon_payments(
                chosen,
                horizon,
                store,
                start_ledger=START,
                end_ledger=END,
                history=(check.horizon_elder_ledger, check.horizon_latest_ledger),
                recorded_at=recorded_at,
            )
            ingest_sac_events(
                chosen, rpc, horizon, store, start_ledger=START, end_ledger=END,
                recorded_at=recorded_at,
            )
    print(f"wrote {target_path} and {len(list(recordings.glob('*.json')))} synthetic exchanges")


if __name__ == "__main__":
    main()
