"""Generate the SYNTHETIC path payment recordings.

Nothing here exists on any network. Accounts, transaction hashes and the SYNUSD asset are
derived from ``invaria:synthetic:stellar:*`` labels. The responses imitate the shapes of
Horizon ``/accounts/{id}/payments`` (joined transactions, failed included) and RPC
``getEvents`` observed in the real recordings, and every response body carries
``"_synthetic"``. The recordings use the replay format of ``ReplayClient`` so the
adapter reads them through exactly the same code as the real samples.

Regenerate (an explicit decision; the tests pin the resulting effects):
    uv run --locked python tests/fixtures/stellar/synthetic/build_path_payments.py
"""

from __future__ import annotations

import base64
import hashlib
import json
import shutil
import struct
import tempfile
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, urlsplit

from invaria.contracts.base import parse_contract
from invaria.contracts.chain import ChainTarget
from invaria.contracts.stellar import NETWORK_PASSPHRASES
from invaria.stellar.adapter import ingest_horizon_payments, ingest_sac_events
from invaria.stellar.http import Response, request_key
from invaria.stellar.sources import Horizon, Rpc, verify_network
from invaria.stellar.store import IngestStore
from invaria.contracts.stellar import encode_account_id
from invaria.stellar.xdr import sac_contract_id

HERE = Path(__file__).resolve().parent
OUT = HERE / "path-payments"
MARK = "SYNTHETIC: generated by build_path_payments.py; does not exist on any network"
NETWORK = "stellar:testnet"
PASSPHRASE = NETWORK_PASSPHRASES[NETWORK]
START, END = 90000100, 90000110
ELDER, LATEST = 90000000, 90000200
BASE_TIME = datetime(2026, 10, 6, 9, 0, tzinfo=UTC)
CAPTURED_AT = "2026-10-06T00:00:00+00:00"
# Unmistakably not testnet: hosts under the reserved .invalid TLD, and ledger numbers far
# beyond testnet's (about 5 million in October 2026).
HORIZON_URL = "https://horizon.synthetic.invalid"
RPC_URL = "https://rpc.synthetic.invalid"
HORIZON_PAGE_LIMIT = 2
RPC_PAGE_LIMIT = 200


def _raw(label: str) -> bytes:
    return hashlib.sha256(f"invaria:synthetic:stellar:{label}".encode()).digest()


def account(label: str) -> str:
    return encode_account_id(_raw(f"account:{label}"))


def tx_hash(label: str) -> str:
    return _raw(f"tx:{label}").hex()


ISSUER = account("synusd-issuer")
EUR_ISSUER = account("eurx-issuer")
A = account("watched")  # the target account
B, C, D, E = (account(x) for x in ("b", "c", "d", "e"))
O1, O2, O3, O4, O5 = (account(f"offer-owner-{i}") for i in range(1, 6))
POOL = _raw("liquidity-pool:synusd-eurx")
SYNUSD = ("SYNUSD", ISSUER)
EURX = ("EURX", EUR_ISSUER)
GBPX = ("GBPX", EUR_ISSUER)
CONTRACT = sac_contract_id(*SYNUSD, PASSPHRASE)


def close_time(ledger: int) -> str:
    return (BASE_TIME + timedelta(seconds=5 * (ledger - START))).strftime("%Y-%m-%dT%H:%M:%SZ")


def toid(ledger: int, order: int, op_index: int) -> int:
    return (ledger << 32) | (order << 12) | (op_index + 1)


# ------------------------------------------------------------------ ScVal (XDR)


def _opaque(data: bytes) -> bytes:
    return struct.pack(">I", len(data)) + data + b"\0" * (-len(data) % 4)


def sc_symbol(text: str) -> str:
    return base64.b64encode(struct.pack(">i", 15) + _opaque(text.encode())).decode()


def sc_string(text: str) -> str:
    return base64.b64encode(struct.pack(">i", 14) + _opaque(text.encode())).decode()


def sc_account(strkey: str) -> str:
    raw = base64.b32decode(strkey)[1:33]
    return base64.b64encode(struct.pack(">iii", 18, 0, 0) + raw).decode()


def sc_pool(raw: bytes) -> str:
    """ScAddress of type 4 (liquidity pool). Undecodable by the adapter in increment 1; a
    typed party since increment 3 (the recordings are unchanged, only their reading)."""
    return base64.b64encode(struct.pack(">ii", 18, 4) + raw).decode()


def sc_i128(value: int) -> str:
    return base64.b64encode(
        struct.pack(">i", 10) + struct.pack(">qQ", value >> 64, value & (2**64 - 1))
    ).decode()


# ------------------------------------------------------------------- the world


def _asset_fields(asset: tuple[str, str] | None, prefix: str = "") -> dict[str, str]:
    if asset is None:
        return {f"{prefix}asset_type": "native"}
    code, issuer = asset
    kind = "credit_alphanum4" if len(code) <= 4 else "credit_alphanum12"
    return {
        f"{prefix}asset_type": kind,
        f"{prefix}asset_code": code,
        f"{prefix}asset_issuer": issuer,
    }


def _transaction(label: str, ledger: int, successful: bool, source: str, ops: int) -> dict[str, Any]:
    return {
        "hash": tx_hash(label),
        "ledger": ledger,
        "successful": successful,
        "source_account": source,
        "fee_account": source,
        "fee_charged": str(100 * ops),
        "memo_type": "none",
    }


def _record(
    label: str, ledger: int, op_index: int, successful: bool, ops: int, fields: dict[str, Any]
) -> dict[str, Any]:
    token = str(toid(ledger, 1, op_index))
    source = fields["from"]
    return {
        "id": token,
        "paging_token": token,
        "transaction_successful": successful,
        "source_account": source,
        "created_at": close_time(ledger),
        "transaction_hash": tx_hash(label),
        "transaction": _transaction(label, ledger, successful, source, ops),
        **fields,
    }


def _path(
    kind: str,
    sender: str,
    receiver: str,
    source: tuple[str, str],
    source_amount: str,
    destination: tuple[str, str],
    amount: str,
    path: list[tuple[str, str]],
    limit: str,
) -> dict[str, Any]:
    fields: dict[str, Any] = {
        "type": kind,
        "from": sender,
        "to": receiver,
        **_asset_fields(destination),
        "amount": amount,
        "path": [_asset_fields(hop) for hop in path],
        "source_amount": source_amount,
        **_asset_fields(source, "source_"),
    }
    fields["source_max" if kind.endswith("receive") else "destination_min"] = limit
    return fields


def _payment(sender: str, receiver: str, asset: tuple[str, str], amount: str) -> dict[str, Any]:
    return {"type": "payment", "from": sender, "to": receiver, **_asset_fields(asset), "amount": amount}


def _event(label: str, ledger: int, op_index: int, index: int, topic: list[str], value: str) -> dict[str, Any]:
    return {
        "type": "contract",
        "ledger": ledger,
        "ledgerClosedAt": close_time(ledger),
        "contractId": CONTRACT,
        "id": f"{toid(ledger, 1, op_index):019d}-{index:010d}",
        "operationIndex": op_index,
        "transactionIndex": 1,
        "txHash": tx_hash(label),
        "inSuccessfulContractCall": True,
        "topic": topic,
        "value": value,
    }


def _transfer(label: str, ledger: int, op: int, index: int, src: str, dst: str, atoms: int) -> dict[str, Any]:
    asset = sc_string(f"{SYNUSD[0]}:{SYNUSD[1]}")
    return _event(label, ledger, op, index, [sc_symbol("transfer"), src, dst, asset], sc_i128(atoms))


def world() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """(Horizon payment records of A, SAC events of SYNUSD), in ledger order."""
    records: list[dict[str, Any]] = []
    events: list[dict[str, Any]] = []
    acc = sc_account
    # 1. strict_send A -> B, SYNUSD -> EURX: Classic debit of A; one SAC leg A -> offer owner.
    records.append(_record("pp-send-debit", 90000101, 0, True, 1, _path(
        "path_payment_strict_send", A, B, SYNUSD, "10.0000000", EURX, "9.5000000", [], "9.0000000")))
    events.append(_transfer("pp-send-debit", 90000101, 0, 1, acc(A), acc(O1), 100000000))
    # 2. strict_receive C -> A, EURX -> SYNUSD bought from two offers: three legs, one credit.
    records.append(_record("pp-receive-multileg", 90000102, 0, True, 1, _path(
        "path_payment_strict_receive", C, A, EURX, "8.1000000", SYNUSD, "7.5000000", [], "20.0000000")))
    events.append(_transfer("pp-receive-multileg", 90000102, 0, 1, acc(O1), acc(C), 30000000))
    events.append(_transfer("pp-receive-multileg", 90000102, 0, 2, acc(O2), acc(C), 45000000))
    events.append(_transfer("pp-receive-multileg", 90000102, 0, 3, acc(C), acc(A), 75000000))
    # 3. strict_send A -> B, EURX -> GBPX through SYNUSD: the target asset is only a hop.
    records.append(_record("pp-intermediate", 90000103, 0, True, 1, _path(
        "path_payment_strict_send", A, B, EURX, "5.0000000", GBPX, "4.0000000", [SYNUSD], "1.0000000")))
    events.append(_transfer("pp-intermediate", 90000103, 0, 1, acc(O3), acc(A), 50000000))
    events.append(_transfer("pp-intermediate", 90000103, 0, 2, acc(A), acc(O4), 50000000))
    # 4. Failed strict_send A -> B: the record still shows amounts, which must be ignored.
    records.append(_record("pp-failed", 90000104, 0, False, 1, _path(
        "path_payment_strict_send", A, B, SYNUSD, "10.0000000", EURX, "9.0000000", [], "9.0000000")))
    # 5. strict_receive D -> A whose SAC legs do not add up to the Classic credit.
    records.append(_record("pp-conflict", 90000105, 0, True, 1, _path(
        "path_payment_strict_receive", D, A, EURX, "2.2000000", SYNUSD, "2.0000000", [], "3.0000000")))
    events.append(_transfer("pp-conflict", 90000105, 0, 1, acc(O5), acc(D), 20000000))
    events.append(_transfer("pp-conflict", 90000105, 0, 2, acc(D), acc(A), 15000000))
    # 6. A plain payment E -> A: still a token movement, one effect across both paths.
    records.append(_record("payment-plain", 90000106, 0, True, 1, _payment(E, A, SYNUSD, "1.0000000")))
    events.append(_transfer("payment-plain", 90000106, 0, 1, acc(E), acc(A), 10000000))
    # 7. strict_send A -> B against a liquidity pool (a typed party since increment 3).
    records.append(_record("pp-pool", 90000107, 0, True, 1, _path(
        "path_payment_strict_send", A, B, SYNUSD, "3.0000000", EURX, "2.9000000", [], "2.0000000")))
    events.append(_transfer("pp-pool", 90000107, 0, 1, acc(A), sc_pool(POOL), 30000000))
    # 8. One transaction, two operations: payment E -> A (op 0) and strict_send A -> B (op 1).
    records.append(_record("mixed-tx", 90000108, 0, True, 2, _payment(E, A, SYNUSD, "2.0000000")))
    records.append(_record("mixed-tx", 90000108, 1, True, 2, _path(
        "path_payment_strict_send", A, B, SYNUSD, "4.0000000", EURX, "3.8000000", [], "3.0000000")))
    events.append(_transfer("mixed-tx", 90000108, 0, 1, acc(E), acc(A), 20000000))
    events.append(_transfer("mixed-tx", 90000108, 1, 2, acc(A), acc(O2), 40000000))
    # 9. A payment E -> A in the LAST ledger of the range: both paths must read it (RPC's
    #    endLedger is exclusive, so the request must ask for END + 1).
    records.append(_record("payment-last-ledger", END, 0, True, 1, _payment(E, A, SYNUSD, "0.5000000")))
    events.append(_transfer("payment-last-ledger", END, 0, 1, acc(E), acc(A), 5000000))
    return records, events


# ------------------------------------------------------------------ responder


class SyntheticNetwork:
    """Answers the adapter's requests from the synthetic world."""

    def __init__(self) -> None:
        self.records, self.events = world()

    def request(self, method: str, url: str, body: bytes | None) -> Response:
        parts = urlsplit(url)
        if method == "POST":
            return self._rpc(json.loads(body or b"{}"))
        query = {k: v[0] for k, v in parse_qs(parts.query).items()}
        path = parts.path
        if path == "/":
            doc: dict[str, Any] = {
                "network_passphrase": PASSPHRASE,
                "history_elder_ledger": ELDER,
                "history_latest_ledger": LATEST,
                "current_protocol_version": 23,
            }
        elif path.startswith("/ledgers/"):
            sequence = int(path.rsplit("/", 1)[1])
            doc = {"sequence": sequence, "closed_at": close_time(sequence)}
        elif path == "/assets":
            doc = {"_embedded": {"records": []}}  # SAC not deployed: derived id accepted
        elif path == f"/accounts/{A}/payments":
            cursor, limit = int(query["cursor"]), int(query["limit"])
            chunk = [r for r in self.records if int(r["paging_token"]) > cursor][:limit]
            doc = {"_embedded": {"records": chunk}}
        else:
            return Response(404, b'{"status": 404}')
        return Response(200, _body(doc))

    def _rpc(self, request: dict[str, Any]) -> Response:
        if request["method"] == "getNetwork":
            return Response(200, _body({"jsonrpc": "2.0", "id": 1, "result": {"passphrase": PASSPHRASE}}))
        params = request["params"]
        pagination = params["pagination"]
        if "cursor" in pagination:
            pool = [e for e in self.events if e["id"] > pagination["cursor"]]
        else:
            # endLedger is exclusive, as in the real RPC.
            pool = [e for e in self.events if params["startLedger"] <= e["ledger"] < params["endLedger"]]
        chunk = pool[: pagination["limit"]]
        # Like the real RPC: a full page ends at its last event; a short one reports how far
        # it scanned (the last ledger of the window, or the latest ledger).
        scanned = params.get("endLedger", LATEST + 1)
        cursor = (
            chunk[-1]["id"]
            if len(chunk) == pagination["limit"]
            else f"{(scanned << 32) - 1:019d}-4294967295"
        )
        result = {"events": chunk, "latestLedger": LATEST, "oldestLedger": ELDER, "cursor": cursor}
        return Response(200, _body({"jsonrpc": "2.0", "id": 1, "result": result}))


def _body(document: dict[str, Any]) -> bytes:
    return json.dumps({"_synthetic": MARK, **document}, indent=1, sort_keys=True).encode() + b"\n"


class DeterministicRecorder:
    """Same file format as ``RecordingClient``, with a fixed capture time and a marker."""

    def __init__(self, inner: SyntheticNetwork, directory: Path) -> None:
        self.inner, self.directory = inner, directory
        directory.mkdir(parents=True, exist_ok=True)

    def request(self, method: str, url: str, body: bytes | None) -> Response:
        response = self.inner.request(method, url, body)
        key = request_key(method, url, body)
        (self.directory / f"{key}.body").write_bytes(response.body)
        meta = {
            "method": method,
            "url": url,
            "request_body": body.decode("utf-8") if body else None,
            "status": response.status,
            "response_sha256": hashlib.sha256(response.body).hexdigest(),
            "captured_at": CAPTURED_AT,
            "synthetic": MARK,
        }
        (self.directory / f"{key}.json").write_text(json.dumps(meta, indent=2, sort_keys=True) + "\n", "utf-8")
        return response


def target_document() -> dict[str, Any]:
    return {
        "schema_version": "1.0",
        "target_id": "synthetic-synusd-path-payments",
        "tenant_id": "tenant-synthetic-stellar",
        "network": NETWORK,
        "asset_code": SYNUSD[0],
        "asset_issuer": SYNUSD[1],
        "account": A,
        "unit": "SYNUSD",
        "instrument_id": f"synthetic:asset:{SYNUSD[0]}:{SYNUSD[1]}",
        "representation_id": f"rep-synthetic-classic-{SYNUSD[0]}-{SYNUSD[1]}",
        "source_id": "stellar-synthetic",
        "expected_sac_contract_id": CONTRACT,
        "synthetic": True,
        "description": "SYNTHETIC path payment cases (build_path_payments.py). The "
        "accounts, transactions and the SYNUSD asset do not exist on any network.",
    }


def main() -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    recordings = OUT / "recordings"
    target_path = OUT / "target.json"
    OUT.mkdir(parents=True)
    target_path.write_text(json.dumps(target_document(), indent=2) + "\n", "utf-8")
    target = parse_contract(ChainTarget, target_path.read_text("utf-8"))
    client = DeterministicRecorder(SyntheticNetwork(), recordings)
    horizon, rpc = Horizon(HORIZON_URL, client), Rpc(RPC_URL, client)
    check = verify_network(horizon, rpc, NETWORK)
    recorded_at = datetime(2026, 10, 6, 10, 0, tzinfo=UTC)
    with tempfile.TemporaryDirectory() as tmp:
        store = IngestStore(Path(tmp))
        ingest_horizon_payments(
            target,
            horizon,
            store,
            start_ledger=START,
            end_ledger=END,
            history=(check.horizon_elder_ledger, check.horizon_latest_ledger),
            recorded_at=recorded_at,
            page_limit=HORIZON_PAGE_LIMIT,
        )
        ingest_sac_events(
            target, rpc, horizon, store, start_ledger=START, end_ledger=END,
            recorded_at=recorded_at, page_limit=RPC_PAGE_LIMIT,
        )
    print(f"wrote {target_path} and {len(list(recordings.glob('*.json')))} synthetic exchanges")


if __name__ == "__main__":
    main()
