"""Generate the SYNTHETIC typed party recordings.

Nothing here exists on any network. Accounts, transaction hashes, balances, contracts,
pools and the SYNUSD/EURX assets are derived from ``invaria:synthetic:stellar:*`` labels
(shared with the other synthetic generators); every response body carries ``"_synthetic"``.

The real samples are ``gdice-issuer-cb-clawback`` (a clawback of a claimable balance and
a creation by the issuer), ``usdc-gdes54wt-cb-create`` and ``usdc-gapnrjhi-cb-claim``
(creation and claim of one balance), ``usdc-gdbxa45u-contract`` (movements with a
contract, listed by Horizon) and the pool legs of ``usdc-gcdkpp``, ``usdc-gazy2f`` and
``usdc-gb4mm``. What they cannot show is covered here:

- a creation whose Classic amount disagrees with the SAC event (conflict);
- a SAC event whose Classic operation Horizon reports as failed, or as another type
  (contradiction);
- a balance whose history Horizon does not find (participants unresolved);
- a claim event of an unsuccessful call (nothing moved);
- a claim of a balance another account created, and its clawback seen by the issuer;
- a clawback from a contract holder (SAC admin call, no Classic side);
- a contract movement Horizon lists, and one it does not list for the account;
- a deposit into a liquidity pool (not a path payment);
- another asset's claimable balance involving the watched account.

Regenerate (an explicit decision; the tests pin the resulting effects):
    uv run --locked python tests/fixtures/stellar/synthetic/build_typed_parties.py
"""

from __future__ import annotations

import base64
import json
import shutil
import struct
import sys
import tempfile
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit

sys.path.insert(0, str(Path(__file__).resolve().parent))

from build_path_payments import (  # noqa: E402
    CONTRACT,
    EURX,
    PASSPHRASE,
    SYNUSD,
    DeterministicRecorder,
    _asset_fields,
    _raw,
    account,
    sc_account,
    sc_i128,
    sc_string,
    sc_symbol,
    tx_hash,
)

from invaria.contracts.base import parse_contract  # noqa: E402
from invaria.contracts.chain import ChainTarget  # noqa: E402
from invaria.contracts.stellar import claimable_balance_hex, encode_strkey  # noqa: E402
from invaria.stellar.adapter import ingest_horizon_payments, ingest_sac_events  # noqa: E402
from invaria.stellar.http import Response, request_key  # noqa: E402
from invaria.stellar.sources import Horizon, Rpc, verify_network  # noqa: E402
from invaria.stellar.store import IngestStore  # noqa: E402
from invaria.stellar.xdr import sac_contract_id  # noqa: E402

HERE = Path(__file__).resolve().parent
OUT = HERE / "typed-parties"
MARK = "SYNTHETIC: generated by build_typed_parties.py; does not exist on any network"
NETWORK = "stellar:testnet"
START, END = 90000500, 90000520
ELDER, LATEST = 90000000, 90000600
BASE_TIME = datetime(2026, 10, 7, 15, 0, tzinfo=UTC)
HORIZON_URL = "https://horizon.synthetic.invalid"
RPC_URL = "https://rpc.synthetic.invalid"

ISSUER = SYNUSD[1]
A = account("typed-watched")  # the watched account
C = account("typed-claimant")
D = account("typed-creator")
E = account("typed-other")
OTHER_CONTRACT = sac_contract_id(*EURX, PASSPHRASE)


def balance(label: str) -> str:
    return encode_strkey("claimable_balance", b"\x00" + _raw(f"claimable-balance:{label}"))


def contract(label: str) -> str:
    return encode_strkey("contract", _raw(f"contract:{label}"))


def pool(label: str) -> str:
    return encode_strkey("liquidity_pool", _raw(f"liquidity-pool:{label}"))


WALLET = contract("typed-wallet")
POOL = pool("synusd-xlm")


def sc_party(strkey: str) -> str:
    """ScAddress of any kind from its strkey (G account, C contract, B balance, L pool)."""
    raw = base64.b32decode(strkey + "=" * (-len(strkey) % 8))[1:-2]
    if strkey.startswith("G"):
        return sc_account(strkey)
    kind = {"C": 1, "B": 3, "L": 4}[strkey[0]]
    if kind == 3:
        return base64.b64encode(struct.pack(">iii", 18, 3, 0) + raw[1:]).decode()
    return base64.b64encode(struct.pack(">ii", 18, kind) + raw).decode()


def close_time(ledger: int) -> str:
    return (BASE_TIME + timedelta(seconds=5 * (ledger - START))).strftime("%Y-%m-%dT%H:%M:%SZ")


def toid(ledger: int, op_index: int) -> int:
    return (ledger << 32) | (1 << 12) | (op_index + 1)


class Case:
    """One transaction with one operation and its SAC events."""

    def __init__(self, label: str, ledger: int, kind: str, source: str, **fields: Any) -> None:
        self.label, self.ledger, self.kind, self.source, self.fields = (
            label,
            ledger,
            kind,
            source,
            fields,
        )
        self.events: list[dict[str, Any]] = []
        self.successful = True
        self.listed_for: set[str] = set()

    @property
    def hash(self) -> str:
        return tx_hash(f"typed:{self.label}")

    def operation(self) -> dict[str, Any]:
        token = str(toid(self.ledger, 0))
        return {
            "id": token,
            "paging_token": token,
            "transaction_successful": self.successful,
            "source_account": self.source,
            "type": self.kind,
            "created_at": close_time(self.ledger),
            "transaction_hash": self.hash,
            **self.fields,
        }

    def event(
        self,
        head: str,
        parties: list[str],
        atoms: int,
        *,
        asset: tuple[str, str] = SYNUSD,
        contract_id: str = CONTRACT,
        successful: bool = True,
    ) -> Case:
        index = len(self.events) + 1
        self.events.append(
            {
                "type": "contract",
                "ledger": self.ledger,
                "ledgerClosedAt": close_time(self.ledger),
                "contractId": contract_id,
                "id": f"{toid(self.ledger, 0):019d}-{index:010d}",
                "operationIndex": 0,
                "transactionIndex": 1,
                "txHash": self.hash,
                "inSuccessfulContractCall": successful,
                "topic": [
                    sc_symbol(head),
                    *(sc_party(p) for p in parties),
                    sc_string(f"{asset[0]}:{asset[1]}"),
                ],
                "value": sc_i128(atoms),
            }
        )
        return self


def _create(amount: str, claimants: list[str], asset: tuple[str, str] = SYNUSD) -> dict[str, Any]:
    return {
        "asset": f"{asset[0]}:{asset[1]}",
        "amount": amount,
        "claimants": [{"destination": c, "predicate": {"unconditional": True}} for c in claimants],
    }


def world() -> tuple[list[Case], dict[str, list[Case]], set[str]]:
    """(cases, history of each claimable balance by strkey, balances Horizon does not find)."""
    histories: dict[str, list[Case]] = {}
    cases: list[Case] = []

    def add(case: Case, *balances: str) -> Case:
        cases.append(case)
        for b in balances:
            histories.setdefault(b, []).append(case)
        return case

    b_ok, b_claim, b_conflict, b_failed, b_missing = (
        balance(x) for x in ("ok", "claim", "conflict", "failed", "missing")
    )
    b_unsuccessful, b_eurx = balance("unsuccessful"), balance("eurx")
    # 1. A creates a balance for C and itself: corroborated, participants resolved.
    add(
        Case("cb-create", 90000501, "create_claimable_balance", A, **_create("2.0000000", [C, A]))
        .event("transfer", [A, b_ok], 20000000),
        b_ok,
    )
    # 2. D created a balance for A (outside the range); A claims it inside the range.
    add(
        Case("cb-create-by-d", 90000400, "create_claimable_balance", D, **_create("3.0000000", [A])),
        b_claim,
    )
    add(
        Case(
            "cb-claim", 90000502, "claim_claimable_balance", A,
            balance_id=claimable_balance_hex(b_claim), claimant=A,
        ).event("transfer", [b_claim, A], 30000000),
        b_claim,
    )
    # 3. The SAC event says 5, the Classic creation 4: a conflict, both kept.
    add(
        Case("cb-conflict", 90000503, "create_claimable_balance", A, **_create("4.0000000", [C]))
        .event("transfer", [A, b_conflict], 50000000),
        b_conflict,
    )
    # 4. Horizon reports the creation as failed, yet a SAC event exists: a contradiction.
    failed = Case("cb-failed-op", 90000504, "create_claimable_balance", A, **_create("1.0000000", [C]))
    failed.event("transfer", [A, b_failed], 10000000).successful = False
    add(failed, b_failed)
    # 5. Horizon does not find the balance's history: participants unresolved.
    add(Case("cb-missing", 90000505, "create_claimable_balance", A).event(
        "transfer", [A, b_missing], 60000000
    ))
    # 6. A claim event of an unsuccessful call: nothing moved.
    add(
        Case("cb-unsuccessful", 90000506, "claim_claimable_balance", A).event(
            "transfer", [b_unsuccessful, A], 70000000, successful=False
        )
    )
    # 7. The issuer claws back the balance A created in case 1 (only the issuer's target
    #    sees it: its party is the balance, not A).
    add(
        Case(
            "cb-clawback", 90000507, "clawback_claimable_balance", ISSUER,
            balance_id=claimable_balance_hex(b_ok),
        ).event("clawback", [b_ok], 20000000),
        b_ok,
    )
    # 8. A clawback from a contract holder: a SAC admin call, no Classic clawback.
    add(
        Case(
            "contract-clawback", 90000508, "invoke_host_function", ISSUER,
            function="HostFunctionTypeHostFunctionTypeInvokeContract",
        ).event("clawback", [WALLET], 8000000)
    )
    # 9. A moves SYNUSD into a contract; Horizon lists the call among A's payments.
    listed = Case(
        "contract-listed", 90000509, "invoke_host_function", A,
        function="HostFunctionTypeHostFunctionTypeInvokeContract",
        asset_balance_changes=[
            {**_asset_fields(SYNUSD), "type": "transfer", "from": A, "to": WALLET,
             "amount": "9.0000000"}
        ],
    ).event("transfer", [A, WALLET], 90000000)
    listed.listed_for.add(A)
    add(listed)
    # 10. The contract moves SYNUSD to A; Horizon does not list the call for A.
    add(
        Case(
            "contract-unlisted", 90000510, "invoke_host_function", E,
            function="HostFunctionTypeHostFunctionTypeInvokeContract",
        ).event("transfer", [WALLET, A], 11000000)
    )
    # 11. A deposits SYNUSD into a liquidity pool (not a path payment).
    add(
        Case("pool-deposit", 90000511, "liquidity_pool_deposit", A).event(
            "transfer", [A, POOL], 12000000
        )
    )
    # 13. A SAC movement into a balance whose operation Horizon reports as a claim: the
    #     Classic type contradicts the event.
    b_wrong = balance("wrong-type")
    add(
        Case(
            "cb-wrong-type", 90000513, "claim_claimable_balance", A,
            balance_id=claimable_balance_hex(b_wrong), claimant=A,
        ).event("transfer", [A, b_wrong], 13000000),
        b_wrong,
    )
    # 12. Another asset's claimable balance created by A: another contract, not this target's.
    add(
        Case(
            "cb-eurx", 90000512, "create_claimable_balance", A,
            **_create("1.0000000", [C], asset=EURX),
        ).event("transfer", [A, b_eurx], 10000000, asset=EURX, contract_id=OTHER_CONTRACT),
        b_eurx,
    )
    return cases, histories, {b_missing}


class SyntheticNetwork:
    def __init__(self) -> None:
        self.cases, self.histories, self.missing = world()

    def request(self, method: str, url: str, body: bytes | None) -> Response:
        if method == "POST":
            return self._rpc(json.loads(body or b"{}"))
        path = urlsplit(url).path
        by_hash = {c.hash: c for c in self.cases}
        by_hex = {claimable_balance_hex(b): b for b in (*self.histories, *self.missing)}
        if path == "/":
            doc: dict[str, Any] = {
                "network_passphrase": PASSPHRASE,
                "history_elder_ledger": ELDER,
                "history_latest_ledger": LATEST,
                "current_protocol_version": 23,
            }
        elif path.startswith("/ledgers/"):
            sequence = int(path.rsplit("/", 1)[1])
            doc = {"sequence": sequence, "closed_at": close_time(sequence)}
        elif path == "/assets":
            doc = {"_embedded": {"records": []}}
        elif path.startswith("/accounts/") and path.endswith("/payments"):
            watched = path.split("/")[2]
            listed = [c.operation() for c in self.cases if watched in c.listed_for]
            doc = {"_embedded": {"records": listed}}
        elif path.startswith("/transactions/") and path.endswith("/operations"):
            case = by_hash.get(path.split("/")[2])
            if case is None:
                return Response(404, _body({"status": 404, "title": "Resource Missing"}))
            doc = {"_embedded": {"records": [case.operation()]}}
        elif path.startswith("/claimable_balances/") and path.endswith("/operations"):
            found = by_hex.get(path.split("/")[2])
            if found is None or found in self.missing:
                return Response(404, _body({"status": 404, "title": "Resource Missing"}))
            doc = {"_embedded": {"records": [c.operation() for c in self.histories[found]]}}
        else:
            return Response(404, _body({"status": 404}))
        return Response(200, _body(doc))

    def _rpc(self, request: dict[str, Any]) -> Response:
        if request["method"] == "getNetwork":
            return Response(
                200, _body({"jsonrpc": "2.0", "id": 1, "result": {"passphrase": PASSPHRASE}})
            )
        params = request["params"]
        pagination = params["pagination"]
        events = [
            e
            for c in self.cases
            for e in c.events
            if e["contractId"] in params["filters"][0]["contractIds"]
        ]
        if "cursor" in pagination:
            chosen = [e for e in events if e["id"] > pagination["cursor"]]
        else:
            chosen = [
                e for e in events if params["startLedger"] <= e["ledger"] < params["endLedger"]
            ]
        chunk = chosen[: pagination["limit"]]
        scanned = params.get("endLedger", LATEST + 1)
        cursor = (
            chunk[-1]["id"]
            if len(chunk) == pagination["limit"]
            else f"{(scanned << 32) - 1:019d}-4294967295"
        )
        result = {"events": chunk, "latestLedger": LATEST, "oldestLedger": ELDER, "cursor": cursor}
        return Response(200, _body({"jsonrpc": "2.0", "id": 1, "result": result}))


def _body(document: dict[str, Any]) -> bytes:
    return json.dumps({"_synthetic": MARK, **document}, indent=1, sort_keys=True).encode() + b"\n"


class Recorder(DeterministicRecorder):
    def request(self, method: str, url: str, body: bytes | None) -> Response:
        response = super().request(method, url, body)
        meta_path = self.directory / f"{request_key(method, url, body)}.json"
        meta = json.loads(meta_path.read_text("utf-8"))
        meta["synthetic"] = MARK
        meta["captured_at"] = "2026-10-07T00:00:00+00:00"
        meta_path.write_text(json.dumps(meta, indent=2, sort_keys=True) + "\n", "utf-8")
        return response


def target_document(target_id: str, account_id: str) -> dict[str, Any]:
    return {
        "schema_version": "1.0",
        "target_id": target_id,
        "tenant_id": "tenant-synthetic-stellar",
        "network": NETWORK,
        "asset_code": SYNUSD[0],
        "asset_issuer": SYNUSD[1],
        "account": account_id,
        "unit": "SYNUSD",
        "instrument_id": f"synthetic:asset:{SYNUSD[0]}:{SYNUSD[1]}",
        "representation_id": f"rep-synthetic-classic-{SYNUSD[0]}-{SYNUSD[1]}",
        "source_id": "stellar-synthetic",
        "expected_sac_contract_id": CONTRACT,
        "synthetic": True,
        "description": "SYNTHETIC typed party cases "
        "(build_typed_parties.py). The accounts, transactions, balances, contracts, pools "
        "and assets do not exist on any network.",
    }


TARGETS = {
    "target-watched.json": ("synthetic-synusd-typed-watched", A),
    "target-issuer.json": ("synthetic-synusd-typed-issuer", ISSUER),
}


def main() -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    recordings = OUT / "recordings"
    OUT.mkdir(parents=True)
    client = Recorder(SyntheticNetwork(), recordings)  # type: ignore[arg-type]
    horizon, rpc = Horizon(HORIZON_URL, client), Rpc(RPC_URL, client)
    check = verify_network(horizon, rpc, NETWORK)
    recorded_at = datetime(2026, 10, 7, 16, 0, tzinfo=UTC)
    for name, (target_id, account_id) in TARGETS.items():
        path = OUT / name
        path.write_text(json.dumps(target_document(target_id, account_id), indent=2) + "\n", "utf-8")
        target = parse_contract(ChainTarget, path.read_text("utf-8"))
        with tempfile.TemporaryDirectory() as tmp:
            store = IngestStore(Path(tmp))
            ingest_horizon_payments(
                target,
                horizon,
                store,
                start_ledger=START,
                end_ledger=END,
                history=(check.horizon_elder_ledger, check.horizon_latest_ledger),
                recorded_at=recorded_at,
            )
            ingest_sac_events(
                target, rpc, horizon, store, start_ledger=START, end_ledger=END,
                recorded_at=recorded_at,
            )
    print(f"wrote {len(TARGETS)} targets and {len(list(recordings.glob('*.json')))} synthetic exchanges")


if __name__ == "__main__":
    main()
