"""Generate the SYNTHETIC muxed account and memo recordings.

Nothing here exists on any network. Accounts, transaction hashes and the SYNUSD asset are
derived from ``invaria:synthetic:stellar:*`` labels (shared with the other synthetic
generators); every response body carries ``"_synthetic"``. The real samples are
``usdc-gbiujq-muxed`` (a payment to a muxed sub-account, its SAC event carrying the u64
sub-account id), ``usdc-gclcz`` (a memo id, carried by the SAC event as the same u64) and
``demoa-own`` (a text memo, carried as a string).

What they cannot show is covered here: the sub-account ids 0 and 2^64 - 1, a muxed sender, a
memo id numerically equal to another payment's sub-account id, hash and return memos (the
same bytes in the SAC event), an empty text memo, a muxed receiver with a memo (the event
carries the sub-account, not the memo), a burn with a memo (no datum), events that
contradict the Classic payment (another sub-account id, another memo, a datum missing), and
a contract call whose u64 datum has no Classic record to tell what it is.

Regenerate (an explicit decision; the tests pin the resulting effects):
    uv run --locked python tests/fixtures/stellar/synthetic/build_muxed.py
"""

from __future__ import annotations

import base64
import json
import shutil
import struct
import sys
import tempfile
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, urlsplit

sys.path.insert(0, str(Path(__file__).resolve().parent))

from build_path_payments import (  # noqa: E402
    CONTRACT,
    PASSPHRASE,
    SYNUSD,
    DeterministicRecorder,
    _asset_fields,
    _opaque,
    account,
    sc_account,
    sc_i128,
    sc_string,
    sc_symbol,
    tx_hash,
)

from invaria.contracts.base import parse_contract  # noqa: E402
from invaria.contracts.chain import ChainTarget  # noqa: E402
from invaria.contracts.stellar import U64_MAX, encode_muxed_account  # noqa: E402
from invaria.stellar.adapter import ingest_horizon_payments, ingest_sac_events  # noqa: E402
from invaria.stellar.http import Response, request_key  # noqa: E402
from invaria.stellar.sources import Horizon, Rpc, verify_network  # noqa: E402
from invaria.stellar.store import IngestStore  # noqa: E402

HERE = Path(__file__).resolve().parent
OUT = HERE / "muxed"
MARK = "SYNTHETIC: generated by build_muxed.py; does not exist on any network"
NETWORK = "stellar:testnet"
START, END = 90000500, 90000530
ELDER, LATEST = 90000000, 90000600
BASE_TIME = datetime(2026, 10, 7, 15, 0, tzinfo=UTC)
HORIZON_URL = "https://horizon.synthetic.invalid"
RPC_URL = "https://rpc.synthetic.invalid"
HORIZON_PAGE_LIMIT = 3

ISSUER = SYNUSD[1]
W = account("muxed-watched")  # the target account (an omnibus-like base account)
S = account("muxed-sender")
HASH = bytes(range(32))
RETURN = bytes(range(32, 64))


def close_time(ledger: int) -> str:
    return (BASE_TIME + timedelta(seconds=5 * (ledger - START))).strftime("%Y-%m-%dT%H:%M:%SZ")


def toid(ledger: int, op_index: int) -> int:
    return (ledger << 32) | (1 << 12) | (op_index + 1)


def sc_u64(value: int) -> bytes:
    return struct.pack(">iQ", 5, value)


def sc_bytes(data: bytes) -> bytes:
    return struct.pack(">i", 13) + _opaque(data)


def sc_text(text: str | bytes) -> bytes:
    raw = text if isinstance(text, bytes) else text.encode()
    return struct.pack(">i", 14) + _opaque(raw)


def movement_map(atoms: int, datum: bytes) -> str:
    """CAP-67 movement data: {amount: i128, to_muxed_id: u64 | string | bytes}."""
    amount_key = base64.b64decode(sc_symbol("amount"))
    datum_key = base64.b64decode(sc_symbol("to_muxed_id"))
    amount = base64.b64decode(sc_i128(atoms))
    return base64.b64encode(
        struct.pack(">iiI", 17, 1, 2) + amount_key + amount + datum_key + datum
    ).decode()


class Case:
    """One Classic payment (or contract call) of SYNUSD and its SAC event."""

    def __init__(
        self,
        label: str,
        ledger: int,
        *,
        sender: str = S,
        receiver: str = W,
        amount: str = "1.0000000",
        from_muxed: int | None = None,
        to_muxed: int | None = None,
        memo: tuple[str, Any] = ("none", None),
        listed: bool = True,
    ) -> None:
        self.label, self.ledger = label, ledger
        self.sender, self.receiver, self.amount = sender, receiver, amount
        self.from_muxed, self.to_muxed, self.memo = from_muxed, to_muxed, memo
        self.listed = listed
        self.events: list[dict[str, Any]] = []

    @property
    def hash(self) -> str:
        return tx_hash(f"muxed:{self.label}")

    @property
    def atoms(self) -> int:
        whole, fraction = self.amount.split(".")
        return int(whole) * 10**7 + int(fraction)

    def transaction(self) -> dict[str, Any]:
        kind, value = self.memo
        doc: dict[str, Any] = {
            "hash": self.hash,
            "ledger": self.ledger,
            "successful": True,
            "source_account": self.sender,
            "fee_account": self.sender,
            "fee_charged": "100",
            "memo_type": kind,
        }
        if kind == "text":
            doc["memo"] = value.decode("utf-8", "replace")
            doc["memo_bytes"] = base64.b64encode(value).decode()
        elif kind == "id":
            doc["memo"] = str(value)
        elif kind in ("hash", "return"):
            doc["memo"] = base64.b64encode(value).decode()
        return doc

    def payment(self) -> dict[str, Any]:
        token = str(toid(self.ledger, 0))
        record: dict[str, Any] = {
            "id": token,
            "paging_token": token,
            "transaction_successful": True,
            "source_account": self.sender,
            "type": "payment",
            "created_at": close_time(self.ledger),
            "transaction_hash": self.hash,
            "transaction": self.transaction(),
            "from": self.sender,
            "to": self.receiver,
            "amount": self.amount,
            **_asset_fields(SYNUSD),
        }
        for side, base, muxed_id in (
            ("from", self.sender, self.from_muxed),
            ("to", self.receiver, self.to_muxed),
        ):
            if muxed_id is not None:
                record[f"{side}_muxed"] = encode_muxed_account(base, muxed_id)
                record[f"{side}_muxed_id"] = str(muxed_id)
        return record

    def event(self, datum: bytes | None, atoms: int | None = None) -> Case:
        """The unified event as CAP-67 emits it, or with the given datum (None: plain) and
        amount."""
        if self.sender == ISSUER:
            topic = [sc_symbol("mint"), sc_account(self.receiver)]
        elif self.receiver == ISSUER:
            topic = [sc_symbol("burn"), sc_account(self.sender)]
        else:
            topic = [sc_symbol("transfer"), sc_account(self.sender), sc_account(self.receiver)]
        topic.append(sc_string(f"{SYNUSD[0]}:{SYNUSD[1]}"))
        amount = self.atoms if atoms is None else atoms
        value = sc_i128(amount) if datum is None else movement_map(amount, datum)
        self.events.append(
            {
                "type": "contract",
                "ledger": self.ledger,
                "ledgerClosedAt": close_time(self.ledger),
                "contractId": CONTRACT,
                "id": f"{toid(self.ledger, 0):019d}-{len(self.events) + 1:010d}",
                "operationIndex": 0,
                "transactionIndex": 1,
                "txHash": self.hash,
                "inSuccessfulContractCall": True,
                "topic": topic,
                "value": value,
            }
        )
        return self

    def operation(self) -> dict[str, Any]:
        """For a contract call: the operation Horizon reports for the transaction."""
        token = str(toid(self.ledger, 0))
        return {
            "id": token,
            "paging_token": token,
            "transaction_successful": True,
            "source_account": self.sender,
            "type": "invoke_host_function",
            "created_at": close_time(self.ledger),
            "transaction_hash": self.hash,
            "function": "HostFunctionTypeInvokeContract",
        }


def world() -> list[Case]:
    return [
        # 1. Muxed receiver, sub-account id 0 (a sub-account, not "absent").
        Case("to-zero", 90000501, to_muxed=0).event(sc_u64(0)),
        # 2. Muxed receiver, the largest u64; never a float.
        Case("to-max", 90000502, to_muxed=U64_MAX).event(sc_u64(U64_MAX)),
        # 3. Muxed sender (CAP-67 never names it) with a text memo: the event carries the memo.
        Case("from-muxed", 90000503, from_muxed=77, memo=("text", b"order 77")).event(
            sc_text("order 77")
        ),
        # 4. A memo id equal to case 5's sub-account id: a memo, never that sub-account.
        Case("memo-id", 90000504, memo=("id", 42)).event(sc_u64(42)),
        # 5. A muxed receiver with sub-account 42 and a memo: the event carries 42, not the memo.
        Case("to-42-with-memo", 90000505, to_muxed=42, memo=("text", b"ignored")).event(sc_u64(42)),
        # 6. Hash and return memos: the same 32 bytes in the event, which cannot tell them apart.
        Case("memo-hash", 90000506, memo=("hash", HASH)).event(sc_bytes(HASH)),
        Case("memo-return", 90000507, memo=("return", RETURN)).event(sc_bytes(RETURN)),
        # 7. An empty text memo is a memo (type text, no bytes), not "none".
        Case("memo-empty", 90000508, memo=("text", b"")).event(sc_text("")),
        # 8. A burn (payment to the issuer) with a memo: burn events carry no datum.
        Case(
            "burn-memo", 90000509, sender=W, receiver=ISSUER, from_muxed=9, memo=("text", b"redeem")
        ).event(None),
        # 9. Contradictions: another sub-account id, another memo, a datum missing.
        Case("bad-muxed-id", 90000510, to_muxed=5).event(sc_u64(6)),
        Case("bad-memo", 90000511, memo=("text", b"A")).event(sc_text("B")),
        Case("missing-datum", 90000512, memo=("id", 7)).event(None),
        # 10. A text memo that is not UTF-8: its exact bytes, in both representations.
        Case("memo-not-utf8", 90000514, memo=("text", b"\xffok")).event(sc_text(b"\xffok")),
        # 11. The datum agrees but the amount does not: a source conflict, never corroborated.
        Case("amount-mismatch", 90000515, memo=("text", b"X")).event(sc_text("X"), 20000000),
        # 12. Another amount with a u64 datum: no copy saying "receiver not muxed" is built.
        Case("amount-mismatch-muxed", 90000516, to_muxed=8).event(sc_u64(8), 30000000),
        # 13. A contract call with a u64 datum: no Classic payment says what it is.
        Case("call-u64", 90000513, listed=False).event(sc_u64(123)),
    ]


class SyntheticNetwork:
    def __init__(self) -> None:
        self.cases = world()

    def request(self, method: str, url: str, body: bytes | None) -> Response:
        parts = urlsplit(url)
        if method == "POST":
            return self._rpc(json.loads(body or b"{}"))
        query = {k: v[0] for k, v in parse_qs(parts.query).items()}
        path = parts.path
        by_hash = {c.hash: c for c in self.cases}
        if path == "/":
            doc: dict[str, Any] = {
                "network_passphrase": PASSPHRASE,
                "history_elder_ledger": ELDER,
                "history_latest_ledger": LATEST,
                "current_protocol_version": 23,
            }
        elif path.startswith("/ledgers/"):
            sequence = int(path.rsplit("/", 1)[1])
            doc = {"sequence": sequence, "closed_at": close_time(sequence)}
        elif path == "/assets":
            doc = {"_embedded": {"records": []}}
        elif path == f"/accounts/{W}/payments":
            cursor, limit = int(query["cursor"]), int(query["limit"])
            records = [c.payment() for c in self.cases if c.listed]
            chunk = [r for r in records if int(r["paging_token"]) > cursor][:limit]
            doc = {"_embedded": {"records": chunk}}
        elif path.startswith("/transactions/") and path.endswith("/operations"):
            case = by_hash.get(path.split("/")[2])
            if case is None:
                return Response(404, _body({"status": 404, "title": "Resource Missing"}))
            doc = {"_embedded": {"records": [case.operation()]}}
        else:
            return Response(404, _body({"status": 404}))
        return Response(200, _body(doc))

    def _rpc(self, request: dict[str, Any]) -> Response:
        if request["method"] == "getNetwork":
            return Response(
                200, _body({"jsonrpc": "2.0", "id": 1, "result": {"passphrase": PASSPHRASE}})
            )
        params = request["params"]
        pagination = params["pagination"]
        events = [e for c in self.cases for e in c.events]
        if "cursor" in pagination:
            pool = [e for e in events if e["id"] > pagination["cursor"]]
        else:
            pool = [e for e in events if params["startLedger"] <= e["ledger"] < params["endLedger"]]
        chunk = pool[: pagination["limit"]]
        scanned = params.get("endLedger", LATEST + 1)
        cursor = (
            chunk[-1]["id"]
            if len(chunk) == pagination["limit"]
            else f"{(scanned << 32) - 1:019d}-4294967295"
        )
        result = {"events": chunk, "latestLedger": LATEST, "oldestLedger": ELDER, "cursor": cursor}
        return Response(200, _body({"jsonrpc": "2.0", "id": 1, "result": result}))


def _body(document: dict[str, Any]) -> bytes:
    return json.dumps({"_synthetic": MARK, **document}, indent=1, sort_keys=True).encode() + b"\n"


class Recorder(DeterministicRecorder):
    def request(self, method: str, url: str, body: bytes | None) -> Response:
        response = super().request(method, url, body)
        meta_path = self.directory / f"{request_key(method, url, body)}.json"
        meta = json.loads(meta_path.read_text("utf-8"))
        meta["synthetic"] = MARK
        meta["captured_at"] = "2026-10-07T00:00:00+00:00"
        meta_path.write_text(json.dumps(meta, indent=2, sort_keys=True) + "\n", "utf-8")
        return response


def target_document() -> dict[str, Any]:
    return {
        "schema_version": "1.0",
        "target_id": "synthetic-synusd-muxed",
        "tenant_id": "tenant-synthetic-stellar",
        "network": NETWORK,
        "asset_code": SYNUSD[0],
        "asset_issuer": SYNUSD[1],
        "account": W,
        "unit": "SYNUSD",
        "instrument_id": f"synthetic:asset:{SYNUSD[0]}:{SYNUSD[1]}",
        "representation_id": f"rep-synthetic-classic-{SYNUSD[0]}-{SYNUSD[1]}",
        "source_id": "stellar-synthetic",
        "expected_sac_contract_id": CONTRACT,
        "synthetic": True,
        "description": "SYNTHETIC muxed account and memo cases "
        "(build_muxed.py). The accounts, transactions and assets do not exist on any network.",
    }


def main() -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    recordings = OUT / "recordings"
    OUT.mkdir(parents=True)
    client = Recorder(SyntheticNetwork(), recordings)  # type: ignore[arg-type]
    horizon, rpc = Horizon(HORIZON_URL, client), Rpc(RPC_URL, client)
    check = verify_network(horizon, rpc, NETWORK)
    recorded_at = datetime(2026, 10, 7, 16, 0, tzinfo=UTC)
    path = OUT / "target.json"
    path.write_text(json.dumps(target_document(), indent=2) + "\n", "utf-8")
    target = parse_contract(ChainTarget, path.read_text("utf-8"))
    with tempfile.TemporaryDirectory() as tmp:
        store = IngestStore(Path(tmp))
        ingest_horizon_payments(
            target,
            horizon,
            store,
            start_ledger=START,
            end_ledger=END,
            history=(check.horizon_elder_ledger, check.horizon_latest_ledger),
            recorded_at=recorded_at,
            page_limit=HORIZON_PAGE_LIMIT,
        )
        ingest_sac_events(
            target,
            rpc,
            horizon,
            store,
            start_ledger=START,
            end_ledger=END,
            recorded_at=recorded_at,
        )
    print(f"wrote 1 target and {len(list(recordings.glob('*.json')))} synthetic exchanges")


if __name__ == "__main__":
    main()
