"""Generate the SYNTHETIC clawback recordings.

Nothing here exists on any network. Accounts, transaction hashes and the SYNUSD/EURX assets
are derived from ``invaria:synthetic:stellar:*`` labels (shared with the other synthetic
generators); every response body carries ``"_synthetic"``. The real samples are
``testusb-holder-clawback``, ``testusb-issuer-clawback`` (an executed account clawback, seen
from the holder and the issuer), ``gdice-issuer-cb-clawback`` (a clawback of a claimable
balance) and ``testusb-failed-clawback`` (a failed clawback operation).

What they cannot show is covered here: a Classic amount that disagrees with the SAC event, an
operation Horizon does not find, a clawback through a contract call, a SAC event whose
Classic operation Horizon reports as failed, an event marked as not successful, another
holder (seen by its own target and by the issuer's), and another asset's clawback.

Regenerate (an explicit decision; the tests pin the resulting effects):
    uv run --locked python tests/fixtures/stellar/synthetic/build_clawbacks.py
"""

from __future__ import annotations

import json
import shutil
import sys
import tempfile
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, urlsplit

sys.path.insert(0, str(Path(__file__).resolve().parent))

from build_path_payments import (  # noqa: E402
    CONTRACT,
    EURX,
    PASSPHRASE,
    SYNUSD,
    DeterministicRecorder,
    _asset_fields,
    account,
    sc_account,
    sc_i128,
    sc_string,
    sc_symbol,
    tx_hash,
)

from invaria.contracts.base import parse_contract  # noqa: E402
from invaria.contracts.chain import ChainTarget  # noqa: E402
from invaria.stellar.adapter import ingest_horizon_payments, ingest_sac_events  # noqa: E402
from invaria.stellar.http import Response, request_key  # noqa: E402
from invaria.stellar.sources import Horizon, Rpc, verify_network  # noqa: E402
from invaria.stellar.store import IngestStore  # noqa: E402
from invaria.stellar.xdr import sac_contract_id  # noqa: E402

HERE = Path(__file__).resolve().parent
OUT = HERE / "clawbacks"
MARK = "SYNTHETIC: generated by build_clawbacks.py; does not exist on any network"
NETWORK = "stellar:testnet"
START, END = 90000300, 90000315
ELDER, LATEST = 90000000, 90000400
BASE_TIME = datetime(2026, 10, 7, 12, 0, tzinfo=UTC)
HORIZON_URL = "https://horizon.synthetic.invalid"
RPC_URL = "https://rpc.synthetic.invalid"

ISSUER = SYNUSD[1]
A = account("clawback-holder-a")
B = account("clawback-holder-b")
OTHER_CONTRACT = sac_contract_id(*EURX, PASSPHRASE)


def close_time(ledger: int) -> str:
    return (BASE_TIME + timedelta(seconds=5 * (ledger - START))).strftime("%Y-%m-%dT%H:%M:%SZ")


def toid(ledger: int, op_index: int) -> int:
    return (ledger << 32) | (1 << 12) | (op_index + 1)


class Case:
    def __init__(self, label: str, ledger: int, kind: str, fields: dict[str, Any]) -> None:
        self.label, self.ledger, self.kind, self.fields = label, ledger, kind, fields
        self.events: list[dict[str, Any]] = []
        self.found = True
        self.successful = True

    @property
    def hash(self) -> str:
        return tx_hash(f"clawback:{self.label}")

    def operation(self) -> dict[str, Any]:
        token = str(toid(self.ledger, 0))
        return {
            "id": token,
            "paging_token": token,
            "transaction_successful": self.successful,
            "source_account": ISSUER,
            "type": self.kind,
            "created_at": close_time(self.ledger),
            "transaction_hash": self.hash,
            **self.fields,
        }

    def event(
        self,
        holder: str,
        atoms: int,
        *,
        asset: tuple[str, str] = SYNUSD,
        contract: str = CONTRACT,
        successful: bool = True,
    ) -> Case:
        index = len(self.events) + 1
        self.events.append(
            {
                "type": "contract",
                "ledger": self.ledger,
                "ledgerClosedAt": close_time(self.ledger),
                "contractId": contract,
                "id": f"{toid(self.ledger, 0):019d}-{index:010d}",
                "operationIndex": 0,
                "transactionIndex": 1,
                "txHash": self.hash,
                "inSuccessfulContractCall": successful,
                "topic": [
                    sc_symbol("clawback"),
                    sc_account(holder),
                    sc_string(f"{asset[0]}:{asset[1]}"),
                ],
                "value": sc_i128(atoms),
            }
        )
        return self


def _clawback(holder: str, amount: str) -> dict[str, Any]:
    return {"from": holder, "amount": amount, **_asset_fields(SYNUSD)}


def world() -> list[Case]:
    cases = [
        # 1. Executed account clawback: Classic and SAC agree.
        Case("ok", 90000301, "clawback", _clawback(A, "3.0000000")).event(A, 30000000),
        # 2. The SAC event says 4; the Classic operation says 3: a conflict, both kept.
        Case("conflict", 90000302, "clawback", _clawback(A, "3.0000000")).event(A, 40000000),
        # 3. A clawback through a contract call: no Classic clawback to compare.
        Case(
            "invoke", 90000304, "invoke_host_function", {"function": "HostFunctionTypeInvokeContract"}
        ).event(A, 5000000),
        # 4. Another holder: seen by its own target and by the issuer's, never by A's.
        Case("other-holder", 90000307, "clawback", _clawback(B, "2.0000000")).event(B, 20000000),
        # 5. Another asset's clawback of A: another contract, never this target's evidence.
        Case("other-asset", 90000308, "clawback", {"from": A, "amount": "1.0000000", **_asset_fields(EURX)}).event(
            A, 10000000, asset=EURX, contract=OTHER_CONTRACT
        ),
    ]
    # 6. Horizon does not find the transaction.
    unknown = Case("not-found", 90000303, "clawback", _clawback(A, "6.0000000")).event(A, 60000000)
    unknown.found = False
    cases.append(unknown)
    # 7. Horizon reports the Classic operation as failed, yet a SAC event exists.
    failed_op = Case("failed-op", 90000305, "clawback", _clawback(A, "7.0000000")).event(A, 70000000)
    failed_op.successful = False
    cases.append(failed_op)
    # 8. An event marked as not successful: never an executed withdrawal.
    cases.append(
        Case("failed-event", 90000306, "clawback", _clawback(A, "8.0000000")).event(
            A, 80000000, successful=False
        )
    )
    return cases


class SyntheticNetwork:
    def __init__(self) -> None:
        self.cases = world()

    def request(self, method: str, url: str, body: bytes | None) -> Response:
        parts = urlsplit(url)
        if method == "POST":
            return self._rpc(json.loads(body or b"{}"))
        path = parts.path
        by_hash = {c.hash: c for c in self.cases}
        if path == "/":
            doc: dict[str, Any] = {
                "network_passphrase": PASSPHRASE,
                "history_elder_ledger": ELDER,
                "history_latest_ledger": LATEST,
                "current_protocol_version": 23,
            }
        elif path.startswith("/ledgers/"):
            sequence = int(path.rsplit("/", 1)[1])
            doc = {"sequence": sequence, "closed_at": close_time(sequence)}
        elif path == "/assets":
            doc = {"_embedded": {"records": []}}
        elif path.startswith("/accounts/") and path.endswith("/payments"):
            doc = {"_embedded": {"records": []}}  # Horizon never lists a clawback here
        elif path.startswith("/transactions/") and path.endswith("/operations"):
            case = by_hash.get(path.split("/")[2])
            if case is None or not case.found:
                return Response(404, _body({"status": 404, "title": "Resource Missing"}))
            doc = {"_embedded": {"records": [case.operation()]}}
        else:
            return Response(404, _body({"status": 404}))
        _ = parse_qs(parts.query)
        return Response(200, _body(doc))

    def _rpc(self, request: dict[str, Any]) -> Response:
        if request["method"] == "getNetwork":
            return Response(
                200, _body({"jsonrpc": "2.0", "id": 1, "result": {"passphrase": PASSPHRASE}})
            )
        params = request["params"]
        pagination = params["pagination"]
        events = [e for c in self.cases for e in c.events if e["contractId"] in params["filters"][0]["contractIds"]]
        if "cursor" in pagination:
            pool = [e for e in events if e["id"] > pagination["cursor"]]
        else:
            pool = [
                e for e in events if params["startLedger"] <= e["ledger"] < params["endLedger"]
            ]
        chunk = pool[: pagination["limit"]]
        scanned = params.get("endLedger", LATEST + 1)
        cursor = (
            chunk[-1]["id"]
            if len(chunk) == pagination["limit"]
            else f"{(scanned << 32) - 1:019d}-4294967295"
        )
        result = {"events": chunk, "latestLedger": LATEST, "oldestLedger": ELDER, "cursor": cursor}
        return Response(200, _body({"jsonrpc": "2.0", "id": 1, "result": result}))


def _body(document: dict[str, Any]) -> bytes:
    return json.dumps({"_synthetic": MARK, **document}, indent=1, sort_keys=True).encode() + b"\n"


class Recorder(DeterministicRecorder):
    def request(self, method: str, url: str, body: bytes | None) -> Response:
        response = super().request(method, url, body)
        meta_path = self.directory / f"{request_key(method, url, body)}.json"
        meta = json.loads(meta_path.read_text("utf-8"))
        meta["synthetic"] = MARK
        meta["captured_at"] = "2026-10-07T00:00:00+00:00"
        meta_path.write_text(json.dumps(meta, indent=2, sort_keys=True) + "\n", "utf-8")
        return response


def target_document(target_id: str, account_id: str) -> dict[str, Any]:
    return {
        "schema_version": "1.0",
        "target_id": target_id,
        "tenant_id": "tenant-synthetic-stellar",
        "network": NETWORK,
        "asset_code": SYNUSD[0],
        "asset_issuer": SYNUSD[1],
        "account": account_id,
        "unit": "SYNUSD",
        "instrument_id": f"synthetic:asset:{SYNUSD[0]}:{SYNUSD[1]}",
        "representation_id": f"rep-synthetic-classic-{SYNUSD[0]}-{SYNUSD[1]}",
        "source_id": "stellar-synthetic",
        "expected_sac_contract_id": CONTRACT,
        "synthetic": True,
        "description": "SYNTHETIC clawback cases (build_clawbacks.py). "
        "The accounts, transactions and assets do not exist on any network.",
    }


TARGETS = {
    "target-holder-a.json": ("synthetic-synusd-clawback-holder-a", A),
    "target-holder-b.json": ("synthetic-synusd-clawback-holder-b", B),
    "target-issuer.json": ("synthetic-synusd-clawback-issuer", ISSUER),
}


def main() -> None:
    if OUT.exists():
        shutil.rmtree(OUT)
    recordings = OUT / "recordings"
    OUT.mkdir(parents=True)
    client = Recorder(SyntheticNetwork(), recordings)  # type: ignore[arg-type]
    horizon, rpc = Horizon(HORIZON_URL, client), Rpc(RPC_URL, client)
    check = verify_network(horizon, rpc, NETWORK)
    recorded_at = datetime(2026, 10, 7, 13, 0, tzinfo=UTC)
    for name, (target_id, account_id) in TARGETS.items():
        path = OUT / name
        path.write_text(json.dumps(target_document(target_id, account_id), indent=2) + "\n", "utf-8")
        target = parse_contract(ChainTarget, path.read_text("utf-8"))
        with tempfile.TemporaryDirectory() as tmp:
            store = IngestStore(Path(tmp))
            ingest_horizon_payments(
                target,
                horizon,
                store,
                start_ledger=START,
                end_ledger=END,
                history=(check.horizon_elder_ledger, check.horizon_latest_ledger),
                recorded_at=recorded_at,
            )
            ingest_sac_events(
                target, rpc, horizon, store, start_ledger=START, end_ledger=END,
                recorded_at=recorded_at,
            )
    print(f"wrote {len(TARGETS)} targets and {len(list(recordings.glob('*.json')))} synthetic exchanges")


if __name__ == "__main__":
    main()
