"""DEX fills as exchange effects, apart from the movements the profiles admit.

The cases come from the SYNTHETIC recordings in ``tests/fixtures/stellar/synthetic/
dex-fills`` (generated by ``build_dex_fills.py``; nothing there exists on any network).
The real fills ``usdc-gbain6`` and ``usdc-issuer-fill`` are covered in ``test_adapter.py``.
"""

from __future__ import annotations

import hashlib
import json
import socket
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pytest

from invaria.contracts.base import parse_contract
from invaria.contracts.chain import ChainTarget, ExecutionLink
from invaria.contracts.observation import ChainEffectPayload, Observation, TokenMovementPayload
from invaria.contracts.stellar import encode_account_id
from invaria.stellar.adapter import (
    RunResult,
    _operation_origin,
    fill_correspondence,
    ingest_horizon_payments,
    ingest_sac_events,
)
from invaria.stellar.http import ReplayClient
from invaria.stellar.sources import Horizon, Page, Rpc, verify_network
from invaria.stellar.store import IngestStore

ROOT = Path(__file__).resolve().parents[1] / "fixtures"
SYNTHETIC = ROOT / "stellar/synthetic/dex-fills"
START, END = 90000200, 90000215
RECORDED_AT = datetime(2026, 10, 7, 10, 0, tzinfo=UTC)
TARGET = parse_contract(ChainTarget, (SYNTHETIC / "target.json").read_text("utf-8"))
A = TARGET.account
HORIZON_URL, RPC_URL = "https://horizon.synthetic.invalid", "https://rpc.synthetic.invalid"


def _account(label: str) -> str:
    raw = hashlib.sha256(f"invaria:synthetic:stellar:account:{label}".encode()).digest()
    return encode_account_id(raw)


def _tx(label: str) -> str:
    return hashlib.sha256(f"invaria:synthetic:stellar:tx:dex:{label}".encode()).hexdigest()


P1, P3, O1, E = (
    _account(x) for x in ("dex-taker-1", "dex-taker-3", "dex-offer-owner-1", "dex-payer")
)


@pytest.fixture(autouse=True)
def no_network(monkeypatch: pytest.MonkeyPatch) -> None:
    def blocked(*_: Any, **__: Any) -> Any:
        raise AssertionError("network access attempted in an offline test")

    monkeypatch.setattr(socket, "socket", blocked)
    monkeypatch.setattr(socket, "create_connection", blocked)
    monkeypatch.setattr(socket, "getaddrinfo", blocked)


def _clients() -> tuple[Horizon, Rpc]:
    client = ReplayClient(SYNTHETIC / "recordings")
    return Horizon(HORIZON_URL, client), Rpc(RPC_URL, client)


def _ingest(store: IngestStore) -> tuple[RunResult, RunResult]:
    horizon, rpc = _clients()
    check = verify_network(horizon, rpc, "stellar:testnet")
    classic = ingest_horizon_payments(
        TARGET,
        horizon,
        store,
        start_ledger=START,
        end_ledger=END,
        history=(check.horizon_elder_ledger, check.horizon_latest_ledger),
        recorded_at=RECORDED_AT,
    )
    sac = ingest_sac_events(
        TARGET, rpc, horizon, store, start_ledger=START, end_ledger=END, recorded_at=RECORDED_AT
    )
    return classic, sac


@pytest.fixture(scope="module")
def run(tmp_path_factory: pytest.TempPathFactory) -> tuple[IngestStore, RunResult, RunResult]:
    store = IngestStore(tmp_path_factory.mktemp("dex"))
    classic, sac = _ingest(store)  # ReplayClient never opens a socket
    return store, classic, sac


def _of(store: IngestStore, label: str) -> list[Observation]:
    return [o for o in store.observations() if o.source.record_key.startswith(_tx(label))]


def _payload(observation: Observation) -> ChainEffectPayload:
    assert isinstance(observation.payload, ChainEffectPayload)
    return observation.payload


def _status(store: IngestStore, label: str) -> str:
    return str(store.current_correspondence()[(TARGET.target_id, _tx(label), 0)]["status"])


def test_the_fixture_is_marked_synthetic() -> None:
    assert TARGET.synthetic and HORIZON_URL.endswith(".invalid") and START > 50_000_000
    for meta in (SYNTHETIC / "recordings").glob("*.json"):
        assert "SYNTHETIC" in json.loads(meta.read_text("utf-8"))["synthetic"]


def test_a_fill_of_the_watched_offer_is_an_exchange_effect(run: Any) -> None:
    """P1's path payment crosses A's offer: the fill is A's effect, not P1's payment."""
    store, _, _ = run
    effects = _of(store, "fill-maker-path")
    assert [o.fact_type for o in effects] == ["chain_effect", "chain_effect"]
    classic, sac = sorted(effects, key=lambda o: _payload(o).representation)
    for observation in (classic, sac):
        payload = _payload(observation)
        assert (payload.effect_kind, payload.account, payload.direction) == (
            "dex_fill",
            A,
            "debit",
        )
        assert payload.units is not None and payload.units.atoms == "30000000"
        assert payload.counterparty is not None and payload.counterparty.id == P1
        assert payload.exchange is not None
        assert (payload.exchange.operation_type, payload.exchange.operation_source) == (
            "path_payment_strict_send",
            P1,
        )
        assert observation.operation_ref is None
    trade = _payload(classic).exchange
    assert trade is not None and trade.offer_id == "7001"
    assert (trade.sold_amount, trade.bought_amount) == ("30000000", "33000000")
    assert trade.sold_asset is not None and trade.sold_asset.startswith("SYNUSD:")
    assert trade.bought_asset is not None and trade.bought_asset.startswith("EURX:")
    # Nothing is attributed to the submitter, and the event between P1 and B is not A's.
    assert all(_payload(o).account == A for o in effects)
    assert _status(store, "fill-maker-path") == "corroborated"


def test_the_watched_accounts_own_offer_operation_is_a_fill_too(run: Any) -> None:
    store, _, _ = run
    effects = _of(store, "fill-taker-manage")
    assert {(_payload(o).direction, _payload(o).counterparty.id) for o in effects} == {  # type: ignore[union-attr]
        ("credit", O1)
    }
    assert _status(store, "fill-taker-manage") == "corroborated"


def test_two_fills_in_one_operation_reconcile_in_aggregate_only(run: Any) -> None:
    store, _, _ = run
    effects = _of(store, "fill-two-offers")
    assert len(effects) == 4  # two trades and two events: none deduplicated
    check = store.current_correspondence()[(TARGET.target_id, _tx("fill-two-offers"), 0)]
    assert check["status"] == "corroborated" and check["claim"] == "aggregate_reconciliation"
    assert check["classic_gross"] == check["sac_gross"] == {"debit": "25000000", "credit": "0"}


def test_fill_conflict_keeps_both_sides_and_quarantines(run: Any) -> None:
    store, _, sac = run
    assert _status(store, "fill-conflict") == "conflict"
    assert {_payload(o).units.atoms for o in _of(store, "fill-conflict")} == {  # type: ignore[union-attr]
        "30000000",
        "40000000",
    }
    conflicts = [e for e in sac.exclusions if e.reason == "CORRESPONDENCE_CONFLICT"]
    assert len(conflicts) == 1 and all(e.quarantine for e in conflicts)


@pytest.mark.parametrize(
    ("label", "reason"),
    [
        ("unresolved-type", "unsupported_operation_type"),
        ("unresolved-not-found", "operation_not_found"),
        ("fill-incomplete", "incomplete_trade_data"),
        # A DEX operation without a trade of A: its type alone does not prove a fill.
        ("fill-sac-only", "incomplete_trade_data"),
    ],
)
def test_an_unresolved_origin_is_kept_and_satisfies_nothing(
    run: Any, label: str, reason: str
) -> None:
    store, _, sac = run
    (effect,) = _of(store, label)
    payload = _payload(effect)
    assert effect.fact_type == "chain_effect" and payload.effect_kind == "unresolved_movement"
    assert payload.unresolved is not None and payload.unresolved.reason == reason
    assert payload.account == A and payload.units is not None
    (exclusion,) = [e for e in sac.exclusions if e.locator == effect.provenance.raw_locator]
    assert exclusion.reason == "UNRESOLVED_ORIGIN" and exclusion.quarantine


def test_listed_payments_and_contract_calls_stay_movements(run: Any) -> None:
    store, _, _ = run
    for label, atoms in (("listed-payment", "9000000"), ("unlisted-invoke", "8000000")):
        movements = _of(store, label)
        assert [o.fact_type for o in movements] == ["token_movement"], label
        assert isinstance(movements[0].payload, TokenMovementPayload)
        assert movements[0].payload.units.atoms == atoms
    # A listed operation is never looked up: its classification needs no second source.
    urls = [
        json.loads(meta.read_text("utf-8"))["url"]
        for meta in (SYNTHETIC / "recordings").glob("*.json")
    ]
    assert not any(_tx("listed-payment") in url for url in urls)
    assert any(_tx("unlisted-invoke") in url for url in urls)
    # Unlisted, the contract call is still a movement but the sources disagree: quarantined.
    _, _, sac = run
    (gap,) = [e for e in sac.exclusions if e.reason == "NOT_LISTED_BY_HORIZON"]
    assert gap.quarantine and gap.locator == _of(store, "unlisted-invoke")[0].provenance.raw_locator


def test_absence_from_the_payments_listing_is_not_a_contradiction(run: Any) -> None:
    store, classic, _ = run
    assert classic.coverage is not None and classic.coverage.is_gap_free
    assert classic.exclusions == ()
    assert len(store.listed_operations()) == 1


def test_every_quarantined_record_names_its_addresses(run: Any) -> None:
    _, _, sac = run
    coverage = sac.coverage
    assert coverage is not None and coverage.quarantined_records is not None
    assert len(coverage.quarantined_records) == coverage.records_quarantined == 11
    for record in coverage.quarantined_records:
        assert record.addresses is not None and A in record.addresses
    fill = next(r for r in coverage.quarantined_records if P1 in (r.addresses or []))
    assert fill.reasons == ["EFFECT_NOT_A_MOVEMENT"]


def test_a_rerun_is_idempotent(run: Any, tmp_path: Path) -> None:
    store, _, first = run
    before = len(store.observations())
    _, again = _ingest(store)
    assert again.appended == () and len(store.observations()) == before
    assert again.coverage == first.coverage


def test_fill_correspondence_rules(run: Any) -> None:
    store, _, _ = run
    classic, sac = sorted(_of(store, "fill-maker-path"), key=lambda o: _payload(o).representation)
    operation = (_tx("fill-maker-path"), 0, START + 1)
    assert fill_correspondence(TARGET, operation, [classic], [sac], False)["status"] == (
        "corroborated"
    )
    assert fill_correspondence(TARGET, operation, [classic], [sac], True)["status"] == (
        "sac_incomplete"
    )
    assert fill_correspondence(TARGET, operation, [], [sac], False)["status"] == "sac_only"
    # Same net, different gross: a debit and a credit of 3 never equal one of 0.
    payload = _payload(sac)
    assert payload.units is not None
    reverse = sac.model_copy(
        update={
            "observation_id": "obs-reverse",
            "payload": payload.model_copy(update={"direction": "credit"}),
        }
    )
    twin = sac.model_copy(update={"observation_id": "obs-twin"})
    record = fill_correspondence(TARGET, operation, [classic], [sac, twin, reverse], False)
    assert record["classic_net"] == record["sac_net"]
    assert record["status"] == "conflict"


def test_two_contents_for_one_fill_leave_it_incomplete(tmp_path: Path) -> None:
    store = IngestStore(tmp_path)
    _ingest(store)
    key = (TARGET.target_id, _tx("fill-maker-path"), 0)
    assert store.current_correspondence()[key]["status"] == "corroborated"
    sac = next(o for o in _of(store, "fill-maker-path") if _payload(o).representation == "sac")
    units = _payload(sac).units
    assert units is not None
    altered = sac.model_copy(
        update={
            "observation_id": "obs-altered-fill",
            "payload": _payload(sac).model_copy(
                update={"units": units.model_copy(update={"atoms": "1"})}
            ),
        }
    )
    store.append_observations([altered])
    _ingest(store)
    assert store.current_correspondence()[key]["status"] == "sac_incomplete"


def test_a_record_on_a_linked_operation_lists_the_link_and_keeps_its_addresses(
    tmp_path: Path,
) -> None:
    """An operation an ExecutionLink names cannot be scoped away by its addresses: its
    records list the linked operation, and their known addresses are kept."""
    link = ExecutionLink(
        schema_version="1.0",
        network="stellar:testnet",
        tx_hash=_tx("fill-conflict"),
        operation_index=0,
        ordinal=0,
        operation_ref="SYN-OP-0001",
        approval_ref="approval-synthetic-test",
        recorded_at=RECORDED_AT,
    )
    store = IngestStore(tmp_path)
    horizon, rpc = _clients()
    check = verify_network(horizon, rpc, "stellar:testnet")
    ingest_horizon_payments(
        TARGET,
        horizon,
        store,
        start_ledger=START,
        end_ledger=END,
        history=(check.horizon_elder_ledger, check.horizon_latest_ledger),
        recorded_at=RECORDED_AT,
        links=[link],
    )
    sac = ingest_sac_events(
        TARGET,
        rpc,
        horizon,
        store,
        start_ledger=START,
        end_ledger=END,
        recorded_at=RECORDED_AT,
        links=[link],
    )
    assert sac.coverage is not None and sac.coverage.quarantined_records is not None
    linked = [r for r in sac.coverage.quarantined_records if r.execution_links]
    # The fill event and the conflicting check of the linked operation.
    assert sorted(r.reasons[0] for r in linked) == [
        "CORRESPONDENCE_CONFLICT",
        "EFFECT_NOT_A_MOVEMENT",
    ]
    for record in linked:
        assert record.execution_links == ["SYN-OP-0001"]
        assert record.chain_operation == f"{_tx('fill-conflict')}:0"
        assert record.addresses is not None and len(record.addresses) >= 2
    # The same run without the link gives the same records, addresses included.
    store = IngestStore(tmp_path / "plain")
    ingest_horizon_payments(
        TARGET,
        horizon,
        store,
        start_ledger=START,
        end_ledger=END,
        history=(check.horizon_elder_ledger, check.horizon_latest_ledger),
        recorded_at=RECORDED_AT,
    )
    plain = ingest_sac_events(
        TARGET, rpc, horizon, store, start_ledger=START, end_ledger=END, recorded_at=RECORDED_AT
    )
    assert plain.coverage is not None and plain.coverage.quarantined_records is not None
    by_locator = {r.locator: r for r in plain.coverage.quarantined_records}
    for record in linked:
        if record.locator in by_locator:
            assert by_locator[record.locator].addresses == record.addresses
            assert by_locator[record.locator].execution_links is None


def test_two_targets_see_one_fill_from_their_own_side(tmp_path: Path) -> None:
    """A's manage offer crosses O1's offer: one SAC event, two perspectives, no collision,
    and each correspondence sums only its own account."""
    owner = parse_contract(ChainTarget, (SYNTHETIC / "target-offer-owner.json").read_text("utf-8"))
    store = IngestStore(tmp_path)
    _ingest(store)
    horizon, rpc = _clients()
    check = verify_network(horizon, rpc, "stellar:testnet")
    ingest_horizon_payments(
        owner,
        horizon,
        store,
        start_ledger=START,
        end_ledger=END,
        history=(check.horizon_elder_ledger, check.horizon_latest_ledger),
        recorded_at=RECORDED_AT,
    )
    second = ingest_sac_events(
        owner, rpc, horizon, store, start_ledger=START, end_ledger=END, recorded_at=RECORDED_AT
    )
    assert second.conflicts == ()
    effects = _of(store, "fill-taker-manage")
    sides = {
        (_payload(o).representation, _payload(o).account, _payload(o).direction) for o in effects
    }
    assert sides == {
        ("classic", A, "credit"),
        ("sac", A, "credit"),
        ("classic", O1, "debit"),
        ("sac", O1, "debit"),
    }
    assert len({o.source.record_key for o in effects}) == 4
    current = store.current_correspondence()
    mine = current[(TARGET.target_id, _tx("fill-taker-manage"), 0)]
    theirs = current[(owner.target_id, _tx("fill-taker-manage"), 0)]
    assert (mine["status"], mine["classic_net"]) == ("corroborated", {A: "20000000"})
    assert (theirs["status"], theirs["classic_net"]) == ("corroborated", {O1: "-20000000"})


class _OddHorizon(Horizon):
    """Horizon whose operations page has an unexpected shape."""

    def __init__(self) -> None:
        super().__init__(HORIZON_URL, ReplayClient(SYNTHETIC / "recordings"))

    def transaction_operations(self, tx_hash: str) -> Page:
        document = {"_synthetic": "test", "_embedded": {"records": [{"type": "payment"}]}}
        raw = json.dumps(document).encode()
        return Page("horizon:odd", raw, hashlib.sha256(raw).hexdigest(), document)


def test_an_odd_horizon_response_leaves_the_origin_unresolved() -> None:
    origin = _operation_origin(
        TARGET, _OddHorizon(), _tx("fill-maker-path"), 0, START + 1, RECORDED_AT
    )
    assert (origin.kind, origin.reason, origin.classic) == (
        "unresolved",
        "incomplete_trade_data",
        (),
    )
