"""Path payments as on-chain effects, apart from business semantics.

The cases come from the SYNTHETIC recordings in ``tests/fixtures/stellar/synthetic/
path-payments`` (generated by ``build_path_payments.py``; nothing there exists on any
network). The real strict_receive sample ``usdc-gb4mm`` is covered in ``test_adapter.py``.
"""

from __future__ import annotations

import base64
import copy
import hashlib
import json
import socket
import struct
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import pytest

from invaria.contracts.base import parse_contract
from invaria.contracts.chain import ChainTarget
from invaria.contracts.observation import (
    ChainEffectPayload,
    ChainParty,
    Observation,
    TokenMovementPayload,
)
from invaria.contracts.stellar import encode_account_id, encode_muxed_account
from invaria.corpus_loader import load_corpus
from invaria.engine.evaluate import evaluate
from invaria.stellar.adapter import (
    Exclusion,
    RunResult,
    _quarantine_records,
    ingest_horizon_payments,
    ingest_sac_events,
    normalize_horizon_record,
    normalize_sac_leg,
    path_correspondence,
)
from invaria.stellar.http import ReplayClient
from invaria.stellar.sources import Horizon, Page, Rpc, verify_network
from invaria.stellar.store import IngestStore

ROOT = Path(__file__).resolve().parents[1] / "fixtures"
SYNTHETIC = ROOT / "stellar/synthetic/path-payments"
START, END = 90000100, 90000110
RECORDED_AT = datetime(2026, 10, 6, 10, 0, tzinfo=UTC)
TARGET = parse_contract(ChainTarget, (SYNTHETIC / "target.json").read_text("utf-8"))
A = TARGET.account
HORIZON_URL, RPC_URL = "https://horizon.synthetic.invalid", "https://rpc.synthetic.invalid"


@pytest.fixture(autouse=True)
def no_network(monkeypatch: pytest.MonkeyPatch) -> None:
    def blocked(*_: Any, **__: Any) -> Any:
        raise AssertionError("network access attempted in an offline test")

    monkeypatch.setattr(socket, "socket", blocked)
    monkeypatch.setattr(socket, "create_connection", blocked)
    monkeypatch.setattr(socket, "getaddrinfo", blocked)


def _clients() -> tuple[Horizon, Rpc]:
    client = ReplayClient(SYNTHETIC / "recordings")
    return Horizon(HORIZON_URL, client), Rpc(RPC_URL, client)


def _classic(store: IngestStore, horizon: Horizon, rpc: Rpc) -> RunResult:
    check = verify_network(horizon, rpc, "stellar:testnet")
    return ingest_horizon_payments(
        TARGET,
        horizon,
        store,
        start_ledger=START,
        end_ledger=END,
        history=(check.horizon_elder_ledger, check.horizon_latest_ledger),
        recorded_at=RECORDED_AT,
        page_limit=2,
    )


def _sac(store: IngestStore, horizon: Horizon, rpc: Rpc) -> RunResult:
    return ingest_sac_events(
        TARGET,
        rpc,
        horizon,
        store,
        start_ledger=START,
        end_ledger=END,
        recorded_at=RECORDED_AT,
        page_limit=200,
    )


@pytest.fixture(scope="module")
def run(tmp_path_factory: pytest.TempPathFactory) -> tuple[IngestStore, RunResult, RunResult]:
    store = IngestStore(tmp_path_factory.mktemp("synthetic-path"))
    horizon, rpc = _clients()
    return store, _classic(store, horizon, rpc), _sac(store, horizon, rpc)


def _tx(label: str) -> str:
    return hashlib.sha256(f"invaria:synthetic:stellar:tx:{label}".encode()).hexdigest()


def _account(label: str) -> str:
    raw = hashlib.sha256(f"invaria:synthetic:stellar:account:{label}".encode()).digest()
    return encode_account_id(raw)


B, C, D, E = (_account(x) for x in ("b", "c", "d", "e"))
O1, O2 = _account("offer-owner-1"), _account("offer-owner-2")


def _effects(store: IngestStore, label: str) -> dict[str, ChainEffectPayload]:
    """Chain effects of one synthetic transaction, by record key suffix after the tx hash."""
    found: dict[str, ChainEffectPayload] = {}
    for o in store.observations():
        if o.source.record_key.startswith(_tx(label)) and isinstance(o.payload, ChainEffectPayload):
            found[o.source.record_key[65:]] = o.payload
    return found


def _correspondence(store: IngestStore, label: str, op_index: int = 0) -> dict[str, Any]:
    (entry,) = [
        e for e in store.correspondence() if (e["tx_hash"], e["op_index"]) == (_tx(label), op_index)
    ]
    return entry


def _op(label: str, op_index: int = 0) -> str:
    return f"{_tx(label)}:{op_index}@SYNUSD:{TARGET.asset_issuer}"


def _exclusions(result: RunResult, reason: str) -> list[Exclusion]:
    return [e for e in result.exclusions if e.reason == reason]


# ------------------------------------------------------------ fixture identity


def test_fixture_is_identified_as_synthetic() -> None:
    assert TARGET.synthetic and "SYNTHETIC" in (TARGET.description or "")
    bodies = sorted((SYNTHETIC / "recordings").glob("*.body"))
    metas = sorted((SYNTHETIC / "recordings").glob("*.json"))
    assert bodies and len(bodies) == len(metas)
    assert all(json.loads(p.read_bytes())["_synthetic"].startswith("SYNTHETIC") for p in bodies)
    assert all(json.loads(p.read_text("utf-8"))["synthetic"] for p in metas)


# ------------------------------------------------------------ Classic effects


def test_strict_send_debit_is_the_executed_source_amount(run: Any) -> None:
    store, _, _ = run
    effects = _effects(store, "pp-send-debit")
    debit = effects["0:classic:debit"]
    assert (debit.effect_kind, debit.account, debit.direction) == ("path_payment_debit", A, "debit")
    assert debit.units is not None and (debit.units.atoms, debit.units.unit) == (
        "100000000",
        "SYNUSD",
    )
    assert debit.counterparty == ChainParty(kind="account", id=B)
    context = debit.path_payment
    assert context is not None and context.operation_type == "path_payment_strict_send"
    # The destination side stays in its own asset, unconverted; destMin (9.0) is never read.
    assert context.destination_asset.startswith("EURX:")
    assert (context.source_amount, context.destination_amount) == ("100000000", "95000000")
    assert "0:classic:credit" not in effects  # EURX is not the watched asset
    assert debit.transaction is not None
    assert (debit.transaction.fee_account, debit.transaction.fee_charged.atoms) == (
        A,
        "100",
    )
    assert debit.transaction.fee_charged.unit == "XLM"


def test_strict_receive_credit_ignores_source_max_and_sums_legs(run: Any) -> None:
    store, _, _ = run
    effects = _effects(store, "pp-receive-multileg")
    credit = effects["0:classic:credit"]
    assert (credit.account, credit.direction) == (A, "credit")
    assert credit.units is not None and credit.units.atoms == "75000000"
    assert credit.path_payment is not None
    assert credit.path_payment.source_amount == "81000000"  # executed, not sendMax (20.0)
    legs = {k: v for k, v in effects.items() if ":sac:" in k}
    assert sorted(legs) == ["0:sac:0", "0:sac:1", "0:sac:2"]
    assert [
        (v.account, v.direction, v.units.atoms if v.units else None) for v in legs.values()
    ] == [
        # Every leg is seen from its sender, whoever the watched account is.
        (O1, "debit", "30000000"),
        (O2, "debit", "45000000"),
        (C, "debit", "75000000"),
    ]
    check = _correspondence(store, "pp-receive-multileg")
    assert check["status"] == "corroborated"
    assert check["classic_net"] == check["sac_net"] == {A: "75000000", C: "0"}


def test_intermediate_only_asset_is_a_note_not_attributed(run: Any) -> None:
    store, classic, sac = run
    effects = _effects(store, "pp-intermediate")
    assert not [k for k in effects if ":classic:" in k]  # nothing attributed to A or B
    assert sorted(k for k in effects if ":sac:" in k) == ["0:sac:0", "0:sac:1"]
    notes = _exclusions(classic, "PATH_INTERMEDIATE_ONLY") + _exclusions(
        sac, "PATH_INTERMEDIATE_ONLY"
    )
    assert len(notes) == 2 and not any(n.quarantine for n in notes)
    assert _correspondence(store, "pp-intermediate")["status"] == "corroborated"


def test_failed_path_payment_keeps_result_and_fee_without_amounts(run: Any) -> None:
    store, classic, _ = run
    failed_tx = _tx("pp-failed")
    assert not any(failed_tx in e.detail for e in classic.exclusions)
    effects = _effects(store, "pp-failed")
    assert list(effects) == ["0:classic:failed"]
    failed = effects["0:classic:failed"]
    assert failed.effect_kind == "path_payment_failed" and not failed.chain.tx_successful
    assert failed.units is None and failed.direction is None
    # The record shows 10.0 / 9.0, but a failed operation executed nothing.
    assert failed.path_payment is not None
    assert (failed.path_payment.source_amount, failed.path_payment.destination_amount) == (
        None,
        None,
    )
    assert failed.transaction is not None and failed.transaction.fee_charged.atoms == "100"
    assert _correspondence(store, "pp-failed")["status"] == "failed_no_effect"
    # A failed operation moved nothing: it is not quarantined (see the coverage test).


def test_correspondence_conflict_keeps_both_sides_and_quarantines(run: Any) -> None:
    store, _, sac = run
    effects = _effects(store, "pp-conflict")
    credit = effects["0:classic:credit"]
    assert credit.units is not None and credit.units.atoms == "20000000"
    assert sorted(k for k in effects if ":sac:" in k) == ["0:sac:0", "0:sac:1"]  # none dropped
    check = _correspondence(store, "pp-conflict")
    assert check["status"] == "conflict"
    assert check["classic_net"] == {A: "20000000", D: "0"}
    assert check["sac_net"] == {A: "15000000", D: "5000000"}
    (conflict,) = [
        e for e in _exclusions(sac, "CORRESPONDENCE_CONFLICT") if e.operation == _op("pp-conflict")
    ]
    assert conflict.quarantine


def test_a_pool_leg_is_a_typed_party_and_the_correspondence_resolves(run: Any) -> None:
    """The liquidity pool of a leg (ScAddress type 4) is a typed
    counterparty, not an account and not its liquidity providers. The leg is kept, so the
    correspondence of A's debit resolves (until increment 3 it stayed sac_incomplete)."""
    store, _, sac = run
    effects = _effects(store, "pp-pool")
    assert sorted(effects) == ["0:classic:debit", "0:sac:0"]
    leg = effects["0:sac:0"]
    assert (leg.account, leg.direction) == (A, "debit")
    assert leg.counterparty is not None and leg.counterparty.kind == "liquidity_pool"
    assert leg.counterparty.id is not None and leg.counterparty.id.startswith("L")
    check = _correspondence(store, "pp-pool")
    assert check["status"] == "corroborated" and check["sac_net"][A] == "-30000000"
    assert not [e for e in sac.exclusions if e.reason == "UNSUPPORTED_PARTY"]


def test_undecodable_leg_party_leaves_the_correspondence_incomplete(run: Any) -> None:
    """A leg party that is no typed party, derived from the synthetic pool leg: a muxed
    account (ScAddress type 2, which CAP-67 never puts in the topics; decoded since
    increment 4, so its M address and the base account are named) or an unknown address
    type (its parties unknown). The leg is not kept and the operation's correspondence stays
    incomplete."""
    store, _, _ = run
    leg = next(
        o for o in store.observations() if o.source.record_key == f"{_tx('pp-pool')}:0:sac:0"
    )
    raw = (store.root / "pages" / f"{leg.provenance.raw_sha256}.json").read_bytes()
    page = Page("synthetic#pp-pool", raw, leg.provenance.raw_sha256, json.loads(raw))
    event = copy.deepcopy(
        next(e for e in page.document["result"]["events"] if e["txHash"] == _tx("pp-pool"))
    )
    muxed = struct.pack(">iiQ", 18, 2, 7) + b"\x01" * 32
    event["topic"][2] = base64.b64encode(muxed).decode()
    operation = next(e for e in store.path_operations() if e["tx_hash"] == _tx("pp-pool"))
    (party,) = normalize_sac_leg(TARGET, event, 0, operation, page, RECORDED_AT)
    assert isinstance(party, Exclusion) and party.reason == "UNSUPPORTED_PARTY"
    m_address = encode_muxed_account(encode_account_id(b"\x01" * 32), 7)
    assert party.quarantine and party.addresses is not None and m_address in party.addresses
    assert party.operation == _op("pp-pool")
    event["topic"][2] = base64.b64encode(struct.pack(">ii", 18, 9) + b"\x01" * 32).decode()
    (unknown,) = normalize_sac_leg(TARGET, event, 0, operation, page, RECORDED_AT)
    assert isinstance(unknown, Exclusion) and unknown.reason == "UNSUPPORTED_PARTY"
    assert unknown.addresses is None
    assert path_correspondence(operation, [], True)["status"] == "sac_incomplete"


def test_a_path_operation_quarantine_names_every_party_of_its_legs(run: Any) -> None:
    """The first leg's record also involves the offer owners of the other legs."""
    store, _, sac = run
    assert sac.coverage is not None and sac.coverage.quarantined_records is not None
    first = next(
        o
        for o in store.observations()
        if o.source.record_key == f"{_tx('pp-receive-multileg')}:0:sac:0"
    )
    (record,) = [
        r for r in sac.coverage.quarantined_records if r.locator == first.provenance.raw_locator
    ]
    assert record.addresses is not None and {A, C, O1, O2} <= set(record.addresses)


def test_quarantine_records_that_do_not_add_up_are_not_scoped(run: Any) -> None:
    store, _, sac = run
    assert sac.coverage is not None
    exact = _quarantine_records(
        TARGET, store, "rpc_sac_events", _pages(store, sac), [], _sac_quarantined(store, sac)
    )
    assert exact is not None
    assert (
        _quarantine_records(TARGET, store, "rpc_sac_events", _pages(store, sac), [], len(exact) + 1)
        is None
    )


def test_quarantine_records_ignore_other_targets_exclusions(tmp_path: Path) -> None:
    store = IngestStore(tmp_path)
    horizon, rpc = _clients()
    _classic(store, horizon, rpc)
    sac = _sac(store, horizon, rpc)
    pages, count = _pages(store, sac), _sac_quarantined(store, sac)
    store.append_exclusions(
        [
            {
                "path": "rpc_sac_events",
                "locator": "rpc:getEvents#foreign-target-event",
                "reason": "EFFECT_NOT_A_MOVEMENT",
                "detail": "another target's record on a shared page",
                "quarantine": True,
                "addresses": [B],
                "target_id": "another-target",
                "page": pages[0],
            }
        ]
    )
    assert _quarantine_records(TARGET, store, "rpc_sac_events", pages, [], count) is not None


def _pages(store: IngestStore, sac: RunResult) -> list[str]:
    checkpoint = store.get_checkpoint(TARGET.target_id, "rpc_sac_events")
    assert checkpoint is not None
    return checkpoint.page_sha256


def _sac_quarantined(store: IngestStore, sac: RunResult) -> int:
    checkpoint = store.get_checkpoint(TARGET.target_id, "rpc_sac_events")
    assert checkpoint is not None
    return checkpoint.records_quarantined


# --------------------------------------------- no double count, no interpretation


def test_plain_payments_stay_movements_and_ops_of_one_tx_are_distinct(run: Any) -> None:
    store, classic, sac = run
    movements = [o for o in store.observations() if o.fact_type == "token_movement"]
    assert sorted(o.source.record_key for o in movements) == sorted(
        [
            f"{_tx('payment-plain')}:0:0",
            f"{_tx('mixed-tx')}:0:0",
            f"{_tx('payment-last-ledger')}:0:0",
        ]
    )
    assert sac.duplicates == 3  # every SAC transfer is the same effect as its payment
    assert [
        (p.from_address, p.to_address, p.units.atoms)
        for p in (o.payload for o in movements)
        if isinstance(p, TokenMovementPayload)
    ] == [(E, A, "10000000"), (E, A, "20000000"), (E, A, "5000000")]
    # Same transaction, operation 1: a path payment, kept as effects, never a movement.
    mixed = _effects(store, "mixed-tx")
    assert sorted(mixed) == ["1:classic:debit", "1:sac:0"]
    assert classic.conflicts == () and sac.conflicts == ()


def test_chain_effects_are_never_linked_nor_movements(run: Any) -> None:
    store, _, _ = run
    effects = [o for o in store.observations() if o.fact_type == "chain_effect"]
    assert len(effects) == 16  # the pool leg is kept since increment 3
    assert all(o.operation_ref is None and o.synthetic for o in effects)
    assert all(isinstance(o.payload, ChainEffectPayload) for o in effects)
    for o in effects:
        page = store.root / "pages" / f"{o.provenance.raw_sha256}.json"
        assert hashlib.sha256(page.read_bytes()).hexdigest() == o.provenance.raw_sha256
    assert {o.provenance.mapping_ref for o in effects} == {
        "stellar-classic-path-effect@1.1.0",
        "stellar-sac-path-leg@1.2.0",
    }


def test_coverage_reflects_path_effects_and_conflicts(run: Any) -> None:
    _, classic, sac = run
    assert classic.coverage is not None and sac.coverage is not None
    # Horizon: 10 records; quarantined: the 5 successful path ops moving SYNUSD.
    assert (classic.coverage.records_received, classic.coverage.records_quarantined) == (10, 5)
    # RPC: 13 events + 7 correspondence checks; quarantined: 5 path ops' legs (the pool
    # leg is a typed leg since increment 3), the conflict and the incomplete check. The SAC
    # certificate also carries the Horizon run it depends on (10 received, 5 quarantined).
    assert (sac.coverage.records_received, sac.coverage.records_quarantined) == (30, 11)
    assert not classic.coverage.is_gap_free and not sac.coverage.is_gap_free


def test_rerun_is_idempotent(tmp_path: Path) -> None:
    store = IngestStore(tmp_path)
    horizon, rpc = _clients()
    _classic(store, horizon, rpc)
    first = _sac(store, horizon, rpc)
    observations, checks = store.observations(), store.correspondence()
    again = _sac(store, horizon, rpc)
    assert store.observations() == observations and store.correspondence() == checks
    assert again.appended == () and again.coverage is not None and first.coverage is not None
    assert again.coverage.records_quarantined == first.coverage.records_quarantined


def test_sac_needs_the_complete_classic_run_of_the_same_range(tmp_path: Path) -> None:
    horizon, rpc = _clients()
    with pytest.raises(ValueError, match="complete Horizon run"):
        _sac(IngestStore(tmp_path / "empty"), horizon, rpc)
    store = IngestStore(tmp_path / "other-range")
    _classic(store, horizon, rpc)
    with pytest.raises(ValueError, match="complete Horizon run"):
        ingest_sac_events(
            TARGET,
            rpc,
            horizon,
            store,
            start_ledger=START,
            end_ledger=END - 1,
            recorded_at=RECORDED_AT,
        )


def test_profiles_do_not_read_chain_effects() -> None:
    """Widening the decoder does not widen subscription or redemption semantics."""
    for name in (
        "subscription-synthetic",
        "subscription-testnet",
        "subscription-testnet-1.1.0",
        "redemption-synthetic",
        "redemption-synthetic-1.4.0",
    ):
        assert "chain_effect" not in (ROOT / "corpus" / name / "profile.json").read_text("utf-8")


@pytest.mark.parametrize("corpus_name", ["subscription-synthetic", "redemption-synthetic"])
def test_engines_ignore_chain_effects_in_the_snapshot(run: Any, corpus_name: str) -> None:
    store, _, _ = run
    corpus = load_corpus(ROOT / "corpus" / corpus_name)
    sample = next(o for o in store.observations() if o.fact_type == "chain_effect")
    for scenario_id in sorted(corpus.scenarios):
        inputs = corpus.inputs_for(scenario_id)
        snapshot = inputs.snapshot
        intruder = sample.model_copy(
            update={
                "observation_id": "obs-chain-effect-intruder",
                "tenant_id": snapshot.tenant_id,
                "instrument_id": next(iter(inputs.observations.values())).instrument_id,
                "recorded_at": snapshot.known_at,
            }
        )
        widened = inputs.__class__(
            snapshot=snapshot.model_copy(
                update={
                    "observation_ids": sorted([*snapshot.observation_ids, intruder.observation_id])
                }
            ),
            profile=inputs.profile,
            observations={**inputs.observations, intruder.observation_id: intruder},
            coverage=inputs.coverage,
            identity_links=inputs.identity_links,
        )
        base, other = evaluate(inputs).result, evaluate(widened).result
        assert other.result == base.result, scenario_id
        assert [c.model_dump() for c in other.controls] == [
            c.model_dump() for c in base.controls
        ], scenario_id


def test_the_last_ledger_of_the_range_is_read_by_both_paths(run: Any) -> None:
    """Regression: RPC's endLedger is exclusive; requesting END left ledger END unread."""
    store, _, sac = run
    last = [
        o
        for o in store.observations()
        if o.source.record_key.startswith(_tx("payment-last-ledger"))
    ]
    assert len(last) == 1 and isinstance(last[0].payload, TokenMovementPayload)
    assert last[0].payload.chain.ledger == END
    assert sac.coverage is not None and sac.coverage.ledger_range is not None
    assert sac.coverage.ledger_range.last == END


def test_rpc_request_asks_for_the_ledger_after_the_range() -> None:
    sent: list[dict[str, Any]] = []

    class _Capture:
        def request(self, method: str, url: str, body: bytes | None) -> Any:
            from invaria.stellar.http import Response

            sent.append(json.loads(body or b"{}"))
            return Response(200, b'{"jsonrpc": "2.0", "id": 1, "result": {"events": []}}')

    Rpc("https://rpc.example", _Capture()).get_events(
        "C" * 56, start_ledger=10, end_ledger=20, cursor=None, limit=5
    )
    assert (sent[0]["params"]["startLedger"], sent[0]["params"]["endLedger"]) == (10, 21)


# ------------------------------------------------------------ unit rules


def _record(**changes: Any) -> tuple[Page, dict[str, Any]]:
    horizon, _ = _clients()
    page = horizon.account_payments(A, str(START << 32), 2)
    record = json.loads(json.dumps(page.document["_embedded"]["records"][0]))
    record.update(changes)
    return page, record


def _normalize(record: dict[str, Any], page: Page) -> list[Observation | Exclusion]:
    return normalize_horizon_record(TARGET, record, page, 0, RECORDED_AT, {})


@pytest.mark.parametrize(
    ("changes", "reason"),
    [
        ({"source_amount": "0.0000000"}, "MALFORMED"),
        ({"source_amount": "-1.0000000"}, "MALFORMED"),
        ({"source_amount": "1.00000001"}, "MALFORMED"),
        ({"path": [{"asset_type": "liquidity_pool_shares"}]}, "MALFORMED"),
        # An M address of another base account than ``to`` cannot be read (increment 4).
        (
            {"to_muxed": "MA7QYNF7SOWQ3GLR2BGMZEHXAVIRZA4KVWLTJJFC7MGXUA74P7UJUAAAAAAAAAAAACJUQ"},
            "MALFORMED",
        ),
    ],
)
def test_path_record_rules(changes: dict[str, Any], reason: str) -> None:
    page, record = _record(**changes)
    (result,) = _normalize(record, page)
    assert isinstance(result, Exclusion) and result.reason == reason


def test_a_muxed_end_keeps_the_path_payment_excluded_with_its_m_address() -> None:
    """Increment 4: a path payment is never evidence of fulfilment; with a muxed
    receiver it stays excluded, now naming the M address and its id, never a holder."""
    page, record = _record()
    muxed = encode_muxed_account(record["to"], 0)  # id 0 is a sub-account, not "absent"
    record.update(to_muxed=muxed, to_muxed_id="0")
    (result,) = _normalize(record, page)
    assert isinstance(result, Exclusion) and result.reason == "MUXED_ACCOUNT"
    assert result.addresses is not None and muxed in result.addresses
    assert record["to"] in result.addresses and "receiver sub-account 0" in result.detail
    record.update(to_muxed_id="1")  # disagrees with the M address
    (malformed,) = _normalize(record, page)
    assert isinstance(malformed, Exclusion) and malformed.reason == "MALFORMED"


def test_fee_must_be_integer_stroops() -> None:
    page, record = _record()
    record["transaction"]["fee_charged"] = "0.0000100"
    (result,) = _normalize(record, page)
    assert isinstance(result, Exclusion) and result.reason == "MALFORMED"


def test_native_and_unrelated_assets_are_out_of_scope() -> None:
    page, record = _record(
        source_asset_type="native", asset_code="EURX", asset_issuer=TARGET.asset_issuer
    )
    record.pop("source_asset_code")
    record.pop("source_asset_issuer")
    assert _normalize(record, page) == []


def test_watched_asset_as_endpoint_and_hop_is_still_an_endpoint() -> None:
    """A route that also passes through SYNUSD does not hide the source debit."""
    page, record = _record(
        path=[
            {
                "asset_type": "credit_alphanum12",
                "asset_code": "SYNUSD",
                "asset_issuer": TARGET.asset_issuer,
            }
        ]
    )
    results = _normalize(record, page)
    assert [r.reason for r in results if isinstance(r, Exclusion)] == ["EFFECT_NOT_A_MOVEMENT"]
    (debit,) = [r for r in results if isinstance(r, Observation)]
    assert isinstance(debit.payload, ChainEffectPayload)
    assert debit.payload.effect_kind == "path_payment_debit"


def test_both_sides_in_the_watched_asset_give_two_distinct_effects() -> None:
    """Source and destination both SYNUSD (A -> A): a debit and a credit, never netted."""
    page, record = _record(
        to=A, asset_code="SYNUSD", asset_type="credit_alphanum12", amount="9.0000000"
    )
    record["asset_issuer"] = TARGET.asset_issuer
    observations = [r for r in _normalize(record, page) if isinstance(r, Observation)]
    payloads = [effect for o in observations if isinstance(effect := o.payload, ChainEffectPayload)]
    assert len(payloads) == len(observations)
    assert [(p.effect_kind, p.units.atoms if p.units else None) for p in payloads] == [
        ("path_payment_debit", "100000000"),
        ("path_payment_credit", "90000000"),
    ]
    assert len({o.source.record_key for o in observations}) == 2


def _operation(**changes: Any) -> dict[str, Any]:
    base = {
        "target_id": TARGET.target_id,
        "watched_asset": f"SYNUSD:{TARGET.asset_issuer}",
        "tx_hash": "ab" * 32,
        "op_index": 0,
        "ledger": START + 1,
        "operation_type": "path_payment_strict_send",
        "successful": True,
        "source_account": A,
        "destination_account": B,
        "source_amount": "100",
        "destination_amount": "90",
        "source_is_target": True,
        "destination_is_target": False,
        "intermediate_only": False,
    }
    return {**base, **changes}


def test_correspondence_statuses_without_legs() -> None:
    assert path_correspondence(_operation(), [], False)["status"] == "classic_only"
    assert path_correspondence(_operation(successful=False), [], False)["status"] == (
        "failed_no_effect"
    )
    assert path_correspondence(_operation(), [], True)["status"] == "sac_incomplete"
    # Nothing on the SAC side is never "corroborated", even if Classic nets to zero.
    assert (
        path_correspondence(_operation(source_is_target=False, intermediate_only=True), [], False)[
            "status"
        ]
        == "no_sac_evidence"
    )


def test_correspondence_flags_legs_on_a_failed_operation(run: Any) -> None:
    store, _, _ = run
    leg = next(
        o
        for o in store.observations()
        if isinstance(o.payload, ChainEffectPayload) and o.payload.effect_kind == "path_payment_leg"
    )
    assert path_correspondence(_operation(successful=False), [leg], False)["status"] == (
        "sac_on_failed_operation"
    )


def test_counterparty_offer_owner_is_not_reconciled(run: Any) -> None:
    """Conversion counterparties (offer owners, pools) are outside the per-account check."""
    store, _, _ = run
    check = _correspondence(store, "pp-send-debit")
    assert O1 not in check["sac_net"] and check["status"] == "corroborated"


# ------------------------------------------------ independent review


def _leg_like(store: IngestStore, account: str, counterparty: str, atoms: str) -> Observation:
    leg = next(
        o
        for o in store.observations()
        if isinstance(o.payload, ChainEffectPayload) and o.payload.effect_kind == "path_payment_leg"
    )
    assert isinstance(leg.payload, ChainEffectPayload) and leg.payload.units is not None
    payload = leg.payload.model_copy(
        update={
            "account": account,
            "direction": "debit",
            "counterparty": ChainParty(kind="account", id=counterparty),
            "units": leg.payload.units.model_copy(update={"atoms": atoms}),
        }
    )
    return leg.model_copy(
        update={"payload": payload, "observation_id": f"obs-{account[:8]}{atoms}"}
    )


def test_self_path_payment_compares_gross_amounts_not_only_the_net(run: Any) -> None:
    """A -> A, debit 100 and credit 101 in Classic; legs -50/+51 net the same +1."""
    store, _, _ = run
    operation = _operation(
        destination_account=A,
        destination_is_target=True,
        source_amount="100",
        destination_amount="101",
    )
    legs = [_leg_like(store, A, O1, "50"), _leg_like(store, O2, A, "51")]
    record = path_correspondence(operation, legs, False)
    assert record["classic_net"] == record["sac_net"] == {A: "1"}
    assert record["status"] == "conflict"
    assert (record["classic_gross"], record["sac_gross"]) == (
        {"debit": "100", "credit": "101"},
        {"debit": "50", "credit": "51"},
    )
    matching = [_leg_like(store, A, O1, "100"), _leg_like(store, O2, A, "101")]
    assert path_correspondence(operation, matching, False)["status"] == "corroborated"


def test_two_targets_in_one_store_keep_separate_indexes_and_identical_legs(
    tmp_path: Path,
) -> None:
    store = IngestStore(tmp_path)
    horizon, rpc = _clients()
    _classic(store, horizon, rpc)
    first = _sac(store, horizon, rpc)
    other = TARGET.model_copy(update={"target_id": "synthetic-synusd-second-target"})
    check = verify_network(horizon, rpc, "stellar:testnet")
    ingest_horizon_payments(
        other,
        horizon,
        store,
        start_ledger=START,
        end_ledger=END,
        history=(check.horizon_elder_ledger, check.horizon_latest_ledger),
        recorded_at=RECORDED_AT,
        page_limit=2,
    )
    second = ingest_sac_events(
        other,
        rpc,
        horizon,
        store,
        start_ledger=START,
        end_ledger=END,
        recorded_at=RECORDED_AT,
    )
    # Canonical legs: the second target sees the same content, never a conflicting copy.
    assert second.conflicts == ()
    assert {e["target_id"] for e in store.path_operations()} == {TARGET.target_id, other.target_id}
    current = store.current_correspondence()
    for (target_id, tx_hash, op_index), entry in current.items():
        twin = current[
            (
                other.target_id if target_id == TARGET.target_id else TARGET.target_id,
                tx_hash,
                op_index,
            )
        ]
        assert (entry["status"], entry["sac_net"]) == (twin["status"], twin["sac_net"])
    assert first.coverage is not None and second.coverage is not None
    assert second.coverage.records_quarantined == first.coverage.records_quarantined


def test_a_changed_leg_set_revises_the_check_and_other_assets_are_ignored(tmp_path: Path) -> None:
    store = IngestStore(tmp_path)
    horizon, rpc = _clients()
    _classic(store, horizon, rpc)
    _sac(store, horizon, rpc)
    key = (TARGET.target_id, _tx("pp-send-debit"), 0)
    before = store.current_correspondence()[key]
    assert before["status"] == "corroborated"
    leg = next(
        o for o in store.observations() if o.source.record_key == f"{_tx('pp-send-debit')}:0:sac:0"
    )
    # A leg of another asset with the same key: not this target's evidence.
    foreign = leg.model_copy(
        update={"observation_id": "obs-foreign-asset", "instrument_id": "synthetic:asset:EURX"}
    )
    assert isinstance(leg.payload, ChainEffectPayload)
    other_network = leg.model_copy(
        update={
            "observation_id": "obs-foreign-network",
            "payload": leg.payload.model_copy(
                update={"chain": leg.payload.chain.model_copy(update={"network": "stellar:pubnet"})}
            ),
        }
    )
    store.append_observations([foreign, other_network])
    _sac(store, horizon, rpc)
    assert store.current_correspondence()[key] == before
    # A second, different content for the same leg: neither copy is chosen nor summed.
    assert isinstance(leg.payload, ChainEffectPayload) and leg.payload.units is not None
    altered = leg.model_copy(
        update={
            "observation_id": "obs-altered-leg",
            "payload": leg.payload.model_copy(
                update={"units": leg.payload.units.model_copy(update={"atoms": "1"})}
            ),
        }
    )
    store.append_observations([altered])
    rerun = _sac(store, horizon, rpc)
    after = store.current_correspondence()[key]
    assert (
        after["status"] == "sac_incomplete"
        and after["evidence_sha256"] != before["evidence_sha256"]
    )
    history = [
        e for e in store.correspondence() if (e["target_id"], e["tx_hash"], e["op_index"]) == key
    ]
    assert [e["status"] for e in history] == ["corroborated", "sac_incomplete"]
    assert rerun.coverage is not None and rerun.coverage.records_quarantined == 7 + 5


def test_synthetic_responses_never_yield_real_observations(tmp_path: Path) -> None:
    horizon, rpc = _clients()
    real_looking = TARGET.model_copy(update={"synthetic": False})
    check = verify_network(horizon, rpc, "stellar:testnet")
    with pytest.raises(ValueError, match="synthetic response for a non-synthetic target"):
        ingest_horizon_payments(
            real_looking,
            horizon,
            IngestStore(tmp_path),
            start_ledger=START,
            end_ledger=END,
            history=(check.horizon_elder_ledger, check.horizon_latest_ledger),
            recorded_at=RECORDED_AT,
            page_limit=2,
        )
    assert HORIZON_URL.endswith(".invalid") and START > 50_000_000


def test_a_store_without_the_path_index_format_is_refused(tmp_path: Path) -> None:
    old = tmp_path / "old"
    old.mkdir()
    (old / "observations.jsonl").write_text("", "utf-8")
    with pytest.raises(ValueError, match="predates"):
        IngestStore(old)
    other = tmp_path / "other"
    other.mkdir()
    for previous in (
        "invaria-ingest-store@1",
        "invaria-ingest-store@3",
        "invaria-ingest-store@7",
    ):
        (other / "FORMAT").write_text(f"{previous}\n", "utf-8")
        with pytest.raises(ValueError, match="format"):
            IngestStore(other)
    assert (IngestStore(tmp_path / "new").root / "FORMAT").read_text("utf-8").strip() == (
        "invaria-ingest-store@8"
    )


class _ShortScanRpc(Rpc):
    """RPC that returns short pages whose cursor shows it did not scan to the end."""

    def __init__(self) -> None:
        super().__init__(RPC_URL, ReplayClient(SYNTHETIC / "recordings"))
        self.calls = 0

    def get_events(self, contract_id: str, **_: Any) -> Page:
        self.calls += 1
        document = {
            "jsonrpc": "2.0",
            "id": 1,
            "result": {
                "events": [],
                "latestLedger": END + 90,
                "cursor": f"{((START + 2) << 32) - 1:019d}-4294967295",
            },
        }
        raw = json.dumps(document).encode()
        return Page(f"rpc:short#{self.calls}", raw, hashlib.sha256(raw).hexdigest(), document)


def test_a_short_page_that_did_not_scan_the_range_is_not_complete(tmp_path: Path) -> None:
    store = IngestStore(tmp_path)
    horizon, rpc = _clients()
    _classic(store, horizon, rpc)
    short = _ShortScanRpc()
    result = ingest_sac_events(
        TARGET,
        short,
        horizon,
        store,
        start_ledger=START,
        end_ledger=END,
        recorded_at=RECORDED_AT,
        max_pages=3,
    )
    assert not result.complete and result.coverage is None and short.calls == 3


def test_path_payment_without_its_transaction_is_malformed() -> None:
    page, record = _record()
    record.pop("transaction")
    (result,) = _normalize(record, page)
    assert isinstance(result, Exclusion) and result.reason == "MALFORMED"


def test_chain_effect_contract_rules(run: Any) -> None:
    store, _, _ = run
    classic = next(
        o.payload
        for o in store.observations()
        if isinstance(o.payload, ChainEffectPayload)
        and o.payload.representation == "classic"
        and o.payload.units is not None
    )
    assert isinstance(classic, ChainEffectPayload) and classic.units is not None
    document = classic.model_dump(mode="json")
    bad = [
        {**document, "effect_kind": "path_payment_leg"},  # a leg must come from SAC
        {**document, "representation": "sac"},  # a debit or credit comes from Classic
        {**document, "transaction": None},  # Classic keeps the transaction outcome
        {**document, "counterparty": None},
        {**document, "units": {**document["units"], "scale": 6}},
        {
            **document,
            "transaction": {
                **document["transaction"],
                "fee_charged": {"atoms": "100", "scale": 7, "unit": "USDC"},
            },
        },
    ]
    for candidate in bad:
        with pytest.raises(ValueError):
            ChainEffectPayload.model_validate(candidate)
    ChainEffectPayload.model_validate(document)
    trade = {
        "operation_type": "manage_sell_offer",
        "operation_source": B,
        "offer_id": "1",
        "sold_asset": "native",
        "sold_amount": "1",
        "bought_asset": "native",
        "bought_amount": "1",
    }
    fill = {**document, "effect_kind": "dex_fill", "path_payment": None, "transaction": None}
    ChainEffectPayload.model_validate({**fill, "exchange": trade})
    no_trade = {k: None for k in trade if k not in ("operation_type", "operation_source")}
    ChainEffectPayload.model_validate(
        {**fill, "representation": "sac", "exchange": {**trade, **no_trade}}
    )
    unresolved = {"reason": "operation_not_found", "operation_type": None}
    for candidate in [
        fill,  # a fill names its exchange
        {**fill, "exchange": {**trade, **no_trade}},  # a Classic fill carries its trade
        {**fill, "representation": "sac", "exchange": trade},  # a SAC fill does not
        {**fill, "exchange": {**trade, "sold_amount": None}},  # all trade fields or none
        {**fill, "exchange": trade, "unresolved": unresolved},
        {**fill, "effect_kind": "unresolved_movement", "unresolved": unresolved},  # SAC only
        {**fill, "effect_kind": "unresolved_movement", "representation": "sac"},  # says why
        {**document, "exchange": trade},  # a path effect is not a fill
    ]:
        with pytest.raises(ValueError):
            ChainEffectPayload.model_validate(candidate)
    ChainEffectPayload.model_validate(
        {
            **fill,
            "effect_kind": "unresolved_movement",
            "representation": "sac",
            "unresolved": unresolved,
        }
    )


def test_the_sac_run_only_uses_its_own_target_index(tmp_path: Path) -> None:
    """Another target's index entry for the plain payment must not turn it into a leg."""
    store = IngestStore(tmp_path)
    horizon, rpc = _clients()
    _classic(store, horizon, rpc)
    store.append_path_operations(
        [
            {
                **_operation(),
                "target_id": "another-target",
                "tx_hash": _tx("payment-plain"),
                "ledger": START + 6,
            }
        ]
    )
    sac = _sac(store, horizon, rpc)
    assert sac.duplicates == 3
    assert not any(
        o.source.record_key.startswith(_tx("payment-plain")) and o.fact_type == "chain_effect"
        for o in store.observations()
    )
